### ISSUE TITLE
How to connect vpn server without login

### ISSUE THREAD

**Issue by rohit1978** [AnchorFreePartner/hydrasdk-demo-android#10]
I used the demo of hydra sdk vpn. If i want to connect vpn server then we need to login account first but i want to connect the server without login button or login popup. Please tell me how to remove login functionality form this sample code.

**Comment by timoshenkoav** [comment]
Hello!
You cannot connect without login. But there is anonymous login where you dont need username/password. You can login with anonymous on app start or on connect button click
