### ISSUE TITLE
Not working with many application users!

### ISSUE THREAD

**Issue by wecrtech** [AnchorFreePartner/hydrasdk-demo-android#100]
Hello Mr/MRs,

I hope your are doing well, i started to work your SDK and it is very good but after my application users increased, many users complains from issues that the app working fine some times then stop working, they cant connect to VPN, I try to track and log the vpn errors and these some of Exceptions:
**NetworkRelatedException** , **transporthydra** ,
I checked my dashboard to see the pricing to pay but i didn't find any pricing plan or limited usage.
Please help me .. What exactly should i do to keep all my users use the VPN connection without any errors and solve stop working issue?

Thanks

**Comment by timoshenkoav** [comment]
Please provide more information on errors you get. Not only the names
NetworkRelatedException - its some networking problem.
