### ISSUE TITLE
Facing SSL issue everytime

### ISSUE THREAD

**Issue by NishaP-UpSquare** [AnchorFreePartner/hydrasdk-demo-android#102]
**NSLocalizedDescription=An SSL error has occurred and a secure connection to the server cannot be made., NSErrorFailingURLKey=https://backend.northghost.com/user/login, NSUnderlyingError=0x28272ca50 {Error Domain=kCFErrorDomainCFNetwork Code=-1200 "(null)" UserInfo={_kCFStreamPropertySSLClientCertificateState=0, _kCFNetworkCFStreamSSLErrorOriginalValue=-9816, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9816}}, _kCFStreamErrorCodeKey=-9816}**

I am getting this issue everytime I try to login or conenct with sdk.

I have tried in iOS 13 & 14 both.Also tried multiple wifi networks and personal mobile data.

**Comment by timoshenkoav** [comment]
Hello!
Please dont use backend.northghost.com. Create your own urls instead
https://pango.gitbook.io/pango-platform/resources/how-to/aws-cloudfront-distribution

**Comment by NishaP-UpSquare** [comment]
I have changed the url as you suggested. Now it's giving me this error

**Error Domain=CTCakeTubeApiErrorDomain Code=600 "Access token is nil"**

**Comment by noshair** [comment]
this link is making problem it connects sometimes and sometimes not
