### ISSUE TITLE
Payment - Bandwidth Related Questions.

### ISSUE THREAD

**Issue by krxstudios** [AnchorFreePartner/hydrasdk-demo-android#108]
Hello,

I tried emailing `partnership@pango.co` but there is no reply.

I made a new project and added my credit card, for unlimited bandwith. 
1) $3 per month is for all users in my project true? not per user?
2) When i check project details i still see `Default Bandwidth limit (Mb)` `50 MB` Could you please help me?
3) On my profile where can i view my added credit cards? and how could i disable auto billing?

Thank you.

**Comment by krxstudios** [comment]
![Screenshot 2020-12-08 at 16 39 16](https://user-images.githubusercontent.com/75682511/101497749-f89d1b00-3973-11eb-8c21-8bc0ff7fec30.png)

EDIT: I see here i can set the user unlimited bandwidth, i will do for all users. I want to know if i'll have to pay $3 per user or $3 is for unlimited users?

Thank you!!!

**Comment by nikslushkin** [comment]
Hello!
3$ for each monthly active premium user. 
By default every user is free and has 50Mb limit. To apply premium status for user you should call the purchase api method https://pango.gitbook.io/pango-platform/console-details/project-settings/user-payment-methods

**Comment by krxstudios** [comment]
@nikslushkin Thank you! How am i able to delete a project and remove my saved credit cards?

**Comment by krxstudios** [comment]
Any help?

**Comment by nikslushkin** [comment]
You can delete your account in settings. To remove your credit card try https://stripe.com/

**Comment by nikslushkin** [comment]
Please check your email for further steps.
