### ISSUE TITLE
Notification

### ISSUE THREAD

**Issue by Alex2105** [AnchorFreePartner/hydrasdk-demo-android#11]
Hello!!!
How clear notification message in Hydra?

**Comment by timoshenkoav** [comment]
Hello
Which notification message do you want to clear?

**Comment by Alex2105** [comment]
When I started the application, I create and initialize HydraSdk in Application, I add a notification during initialization (HydraSdk.init (this, clientInfo notification, hydraSDKConfig)), but when I clear applications from back stack, the notification continues to live, I tried to clear with update, but it doesn't work (HydraSdk.update (NotificationConfig.newBuilder (). disabled (). build ()))

**Comment by timoshenkoav** [comment]
what is you config for notification in HydraSdk.init call?

**Comment by Alex2105** [comment]
val notification = NotificationConfig.newBuilder()
            .channelId("Hydra_notification")
            .title("Vk Vpn")
            .clickAction(HydraSdk.EXTRA_FROM_NOTIFICATION)
            .build()

**Comment by Alex2105** [comment]
In method init, Hydra Sdk take NotificationConfig class

**Comment by timoshenkoav** [comment]
notification for what state you cannot clear? idle/connected?
You can pass disabled NotificationConfig, it will not show notifications
NotificationConfig notificationConfig = NotificationConfig.newBuilder()
                .title(getResources().getString(R.string.app_name))
                .channelId(CHANNEL_ID)
                .disabled()
                .build();
