### ISSUE TITLE
Can't register in anchorfree

### ISSUE THREAD

**Issue by cellojaan** [AnchorFreePartner/hydrasdk-demo-android#110]
I can not register and buy service from developer.anchorfree.com

Website says always this error:
https://i.ibb.co/NLFYDBv/Ekran-Resmi-2020-12-23-17-01-29.png

Any idea?

**Comment by nikslushkin** [comment]
Hi @cellojaan ! Thanks for letting us know. Could you please try again? issue should be fixed

**Comment by cellojaan** [comment]
> Hi @cellojaan ! Thanks for letting us know. Could you please try again? issue should be fixed

Now the problem I can not buy premium. The page always loading like this:
https://ibb.co/GPFz7SC

Can you fix it please?
