### ISSUE TITLE
console Exception ..how to fix that

### ISSUE THREAD

**Issue by zaeem-code** [AnchorFreePartner/hydrasdk-demo-android#111]
java.lang.IllegalStateException
k.j0.k.f.<clinit>
Crash
1,385
43
37 minutes ago
java.lang.IllegalArgumentException
i.d.a.b.c.onClick
Crash
101
70
3 hours ago
java.lang.NullPointerException
k.j0.k.f.<clinit>
Crash
86
2
11 hours ago
java.lang.IllegalArgumentException
i.d.a.b.c.onClick
Crash
51
31
6 hours ago
base.apk (offset 0xd27000)
Crash
33
22
55 minutes ago
base.apk (offset 0xd27000)
Crash
33
20
3 hours ago
abort
Crash
22
13
3 hours ago
java.lang.OutOfMemoryError
i.b.b.j.b
Crash
18
18
2 hours ago
signal 5 (SIGTRAP), code 1 (TRAP_BRKPT)
Chrome.apk (offset 0xfb4000)
Crash
15
13
11 hours ago
base.apk (offset 0xdf3000)
Crash
15
11
2 hours ago
java.lang.OutOfMemoryError
i.b.b.j.d
Crash
13
12
8 hours ago
abort
Crash
12
9
12 hours ago
base.apk (offset 0xc0c000)
Crash
10
9
97 minutes ago
signal 5 (SIGTRAP), code 4 (TRAP_HWBKPT)
Chrome.apk (offset 0xf2d000)
Crash
8
4
5 hours ago
base.apk (offset 0xc0c000)

**Comment by timoshenkoav** [comment]
What is that and how is it related to SDK?

**Comment by zaeem-code** [comment]
because i use you hydra sdk and it give me that exception

**Comment by timoshenkoav** [comment]
What exception? exception can be only in sdk? Please do at least code deobfuscation for each exception, as k.j0.k.f. is not very handy

**Comment by timoshenkoav** [comment]
any news on this?
