### ISSUE TITLE
Can't Upgrade my plan to Premium

### ISSUE THREAD

**Issue by mwaked** [AnchorFreePartner/hydrasdk-demo-android#112]
I am trying to upgrade my plan to Premium but it keeps loading 30 minutes and nothing happen!

<img width="1377" alt="Screen Shot 2021-01-15 at 1 28 11 PM" src="https://user-images.githubusercontent.com/33099498/104714122-3ee95500-573e-11eb-8b63-602c79678bbb.png">

**Comment by mwaked** [comment]
Any update?
please help me to upgrade my plan to premium.

**Comment by timoshenkoav** [comment]
Please check. It should be fixed now
