### ISSUE TITLE
increase bandwidth limit upto 1gb for each free user current 50mb bandwidth is not sufficient to engage users in app

### ISSUE THREAD

**Issue by Vishusarkar** [AnchorFreePartner/hydrasdk-demo-android#113]

**Comment by nikslushkin** [comment]
Hello @Vishusarkar ! 
Thanks for interesting in our SDK.
It is really great that you want to provide more bandwidth to your users. 
Please send us details about your project to partnership@pango.co .
We can discuss a custom agreement and pricing for your users.

**Comment by Vishusarkar** [comment]
Hi I just upgraded my project to premium plan but still my project has a limit of 50mb for free users why??? Please increase it to 1gb per user per day for free users
