### ISSUE TITLE
UnifiedSDK.update() NoSuchMethodError

### ISSUE THREAD

**Issue by Nevaehy** [AnchorFreePartner/hydrasdk-demo-android#116]
Got this error on some real devices (API 24, 28, 30) and some AVD (API 22, 19)

java.lang.NoSuchMethodError: No static method update(Lcom/anchorfree/sdk/NotificationConfig;)V in class Lcom/anchorfree/sdk/UnifiedSDK; or its super classes (declaration of 'com.anchorfree.sdk.UnifiedSDK' appears in /data/app/com.blazing.fast.vpn-1/base.apk)

**Comment by Nevaehy** [comment]
The code is:

```
private fun initHydraSdk() {
        val notificationConfig = NotificationConfig.newBuilder()
                .disabled()
                .build()
        UnifiedSDK.update(notificationConfig)

        val clientInfo = ClientInfo.newBuilder()
            .baseUrl(resources.getString(R.string.host_url_key))
            .carrierId(resources.getString(R.string.carrier_id_key))
            .build()
        val transportConfigList: MutableList<TransportConfig> = ArrayList()
        transportConfigList.add(HydraTransportConfig.create())
        transportConfigList.add(OpenVpnTransportConfig.tcp())
        transportConfigList.add(OpenVpnTransportConfig.udp())
        UnifiedSDK.update(transportConfigList, CompletableCallback.EMPTY)
        val config = UnifiedSDKConfig.newBuilder().idfaEnabled(false).build()
        UnifiedSDK.getInstance(clientInfo, config)
        UnifiedSDK.setLoggingLevel(Log.VERBOSE)
        UnifiedSDK.addVpnStateListener(this)
    }
```

**Comment by timoshenkoav** [comment]
no idea, method is there. Maybe its due to kotlin issue to call static methods on java interfaces. Try to add 
 kotlinOptions {
        jvmTarget = '1.8'
    }

**Comment by Nevaehy** [comment]
> 
> 
> no idea, method is there. Maybe its due to kotlin issue to call static methods on java interfaces. Try to add
> kotlinOptions {
> jvmTarget = '1.8'
> }

This code is already present

**Comment by timoshenkoav** [comment]
we've checked the sdk on devices with api levels you've mentioned. no issue exits. Maybe you have some custom proguard settings?

**Comment by Nevaehy** [comment]
> 
> 
> we've checked the sdk on devices with api levels you've mentioned. no issue exits. Maybe you have some custom proguard settings?

Proguard is empty. Also I tried settings that you specified in Readme. Had the same outcome.

**Comment by timoshenkoav** [comment]
from where do you have this stacktrace? just in logs? or in some crash logging system like firebase?

**Comment by Nevaehy** [comment]
Just in logs when I'm trying to launch app on AVD in Android Studio

**Comment by timoshenkoav** [comment]
ah, you can just skip it. it's just system logs, it still should work

**Comment by Nevaehy** [comment]
No, it doesn't. App crashes.

**Comment by Nevaehy** [comment]
![123](https://user-images.githubusercontent.com/8986848/108250801-5bbee100-715f-11eb-8c6a-2441de3f64d4.png)

**Comment by Nevaehy** [comment]
@timoshenkoav could you please reopen issue?

**Comment by Nevaehy** [comment]
At first, I've created an app that uses your SDK. Everything worked fine.
Then, I've created a module (.aar) from this app and implemented it in absolutely clean, new project. And in this new project I've got this error.

**Comment by timoshenkoav** [comment]
just tried the app from this repo on AVD 22 - no crashes. Please check your app settings - dont think its sdk issue

**Comment by timoshenkoav** [comment]
if you made a lib check if you have runtime dependencies specified

**Comment by Nevaehy** [comment]
> 
> 
> if you made a lib check if you have runtime dependencies specified

other APIs work fine, then all lib dependencies are fine too?

**Comment by timoshenkoav** [comment]
UnifiedSDK.update(notificationConfig)         is the first api you call. what api do you call before?

**Comment by timoshenkoav** [comment]
try to build and run the app from this repo on the same device/avd

**Comment by Nevaehy** [comment]
> 
> 
> UnifiedSDK.update(notificationConfig) is the first api you call. what api do you call before?

Nothing. I've tried .init() and others, but any api call results in crash and the same stacktrace error

**Comment by timoshenkoav** [comment]
so i suggest its dependency error. how do you specify the sdk dependency in aar library module? as 'implementation'? try the 'api'

**Comment by Nevaehy** [comment]
> 
> 
> so i suggest its dependency error. how do you specify the sdk dependency in aar library module? as 'implementation'? try the 'api'

    implementation 'com.github.AnchorFreePartner.hydra-sdk-android:sdk:3.3.3'
    implementation 'com.github.AnchorFreePartner.hydra-sdk-android:openvpn:3.3.3'

**Comment by timoshenkoav** [comment]
try to change implementation to api

**Comment by Nevaehy** [comment]
> 
> 
> try to change implementation to api

Just tried. Nothing has changed :(

**Comment by timoshenkoav** [comment]
hard to tell, try to build the app from this repo and run on the same avd/device - it should work

**Comment by Nevaehy** [comment]
Yep, I also tried it. It worked as a separate app, but not as an implemented module.

**Comment by timoshenkoav** [comment]
so you implemented it wrong

**Comment by timoshenkoav** [comment]
can you share your complete project sources that reproduce the issue?

**Comment by Nevaehy** [comment]
can I send link to repo via email?

**Comment by timoshenkoav** [comment]
sure - a.timoshenko@anchorfree.com

**Comment by Nevaehy** [comment]
> 
> 
> sure - [a.timoshenko@anchorfree.com](mailto:a.timoshenko@anchorfree.com)

Great, thanks!
Just sent you a message.

**Comment by timoshenkoav** [comment]
Do you have a requirement to make it as aar? Why not just do a library module in app module and add it as dependency

**Comment by Nevaehy** [comment]
yep, it's a requirement

**Comment by timoshenkoav** [comment]
ok, move vpn.aar to app/libs folder
and add 
implementation fileTree(dir: 'libs', include: ['*.aar'])
to app build.gradle
![image](https://user-images.githubusercontent.com/1254369/108275908-4fdf1900-7177-11eb-9aea-4ca981275c1e.png)
![image](https://user-images.githubusercontent.com/1254369/108275927-553c6380-7177-11eb-91ef-4b28397cf8bc.png)

**Comment by Nevaehy** [comment]
Now I cannot go to VPNMainActivity because it's as unresolved reference now

**Comment by timoshenkoav** [comment]
you did something wrong
![Uploading image.png…]()

**Comment by timoshenkoav** [comment]
i'm sending working project to you

**Comment by Nevaehy** [comment]
Should I keep 
1. include ':vpn' in settings.gradle
2. vpn folder with .aar and .gradle file inside the project?

**Comment by timoshenkoav** [comment]
1. no, you can remove it
2.no, you can remove it

**Comment by Nevaehy** [comment]
I removed both and now it's unresolved reference for VPNMainActivity.. :)

**Comment by timoshenkoav** [comment]
check your email

**Comment by Nevaehy** [comment]
It works now, thank you!

But may I know the reason? Why didn't implementation project() work?

**Comment by timoshenkoav** [comment]
not sure, maybe its something with classloader

**Comment by abkoradiya** [comment]
@timoshenkoav I am getting this error when build aar file and use it.
What is the solution?
