### ISSUE TITLE
I getting error while initiation of hydra sdk is done

### ISSUE THREAD

**Issue by MPVIRANIDEVELOPER** [AnchorFreePartner/hydrasdk-demo-android#124]
E/USDK-DefaultTrackerTra(23194): javax.net.ssl.SSLHandshakeException: Connection closed by peer
E/USDK-DefaultTrackerTra(23194): 	at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
E/USDK-DefaultTrackerTra(23194): 	at com.android.org.conscrypt.SslWrapper.doHandshake(SslWrapper.java:381)
E/USDK-DefaultTrackerTra(23194): 	at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:222)
E/USDK-DefaultTrackerTra(23194): 	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:320)
E/USDK-DefaultTrackerTra(23194): 	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:284)
E/USDK-DefaultTrackerTra(23194): 	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:169)
E/USDK-DefaultTrackerTra(23194): 	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:258)
E/USDK-DefaultTrackerTra(23194): 	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
E/USDK-DefaultTrackerTra(23194): 	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
E/USDK-DefaultTrackerTra(23194): 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
E/USDK-DefaultTrackerTra(23194): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
E/USDK-DefaultTrackerTra(23194): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
E/USDK-DefaultTrackerTra(23194): 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
E/USDK-DefaultTrackerTra(23194): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
E/USDK-DefaultTrackerTra(23194): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
E/USDK-DefaultTrackerTra(23194): 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
E/USDK-DefaultTrackerTra(23194): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
E/USDK-DefaultTrackerTra(23194): 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:127)
E/USDK-DefaultTrackerTra(23194): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
E/USDK-DefaultTrackerTra(23194): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
E/USDK-DefaultTrackerTra(23194): 	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:257)
E/USDK-DefaultTrackerTra(23194): 	at okhttp3.RealCall.execute(RealCall.java:93)
E/USDK-DefaultTrackerTra(23194): 	at com.anchorfree.ucr.transport.DefaultTrackerTransport.upload(DefaultTrackerTransport.java:145)
E/USDK-DefaultTrackerTra(23194): 	at com.anchorfree.ucr.EventsTracker.uploadForTracker(EventsTracker.java:243)
E/USDK-DefaultTrackerTra(23194): 	at com.anchorfree.ucr.EventsTracker.lambda$performUpload$2$EventsTracker(EventsTracker.java:208)
E/USDK-DefaultTrackerTra(23194): 	at com.anchorfree.ucr.-$$Lambda$EventsTracker$n5yv4ZUOVo1Sykw_Ghihebt2qJw.run(Unknown Source:2)
E/USDK-DefaultTrackerTra(23194): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
E/USDK-DefaultTrackerTra(23194): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
E/USDK-DefaultTrackerTra(23194): 	at java.lang.Thread.run(Thread.java:764)

**Comment by timoshenkoav** [comment]
Its just a log, you can ignore it
