### ISSUE TITLE
Debugging Problem

### ISSUE THREAD

**Issue by Trushhackyou** [AnchorFreePartner/hydrasdk-demo-android#126]
Could not GET 'https://www.jitpack.io/com/github/AnchorFree/hydra-vpn-android/hydratransport/0.17.34/hydratransport-0.17.34.pom'. Received status code 401 from server: Unauthorized
Disable Gradle 'offline mode' and sync project
Help me with this issue.
![Screenshot (115)](https://user-images.githubusercontent.com/50118284/117665017-08898700-b1c0-11eb-93f2-3f29ca483d4d.png)

**Comment by hassanishaq847** [comment]
@Trushhackyou same issue i am facing with source code. My app is live on play console.
May be these SDKs are private now and restricted to use by the admin

**Comment by csabii** [comment]
+1-ing this issue

**Comment by haseebkamanger** [comment]
Same issue here

**Comment by Shvet** [comment]
Same problem here

**Comment by csabii** [comment]
transport is now ok bu I still get this:

Could not GET 'https://www.jitpack.io/com/github/AnchorFreePartner/toolkit-android/toolkit/1.5.7/toolkit-1.5.7.pom'. Received status code 401 from server: Unauthorized
Disable Gradle 'offline mode' and sync project

**Comment by timoshenkoav** [comment]
try now. For some reason jitpack sometimes reset the public read permission for project

**Comment by Shvet** [comment]
Its working on window system but on mac system its not working. any reason for this?

**Comment by yogeshwar-quantum4u** [comment]
> try now. For some reason jitpack sometimes reset the public read permission for project

Could you please help me out in issue #125, we are unable to register the purchase json on your console. its always returning the parse error. We are stuck there. Already have the premium account of your sdk. Please update us and guide us on that issue.

**Comment by csabii** [comment]
Hi Timo,

Could you please make 2.0.0 related libs available as well? Unfortunately I am not at liberty to update the project with 3.x.x version of hydra.

the error I get is:
Could not GET 'https://www.jitpack.io/com/github/AnchorFreePartner/hydra-vpn-android/corevpn/0.14.1/corevpn-0.14.1.pom'. Received status code 401 from server: Unauthorized
Disable Gradle 'offline mode' and sync project

Thank you
