### ISSUE TITLE
Not working on some android 5 devices 

### ISSUE THREAD

**Issue by singhmeenu** [AnchorFreePartner/hydrasdk-demo-android#130]
Hi @timoshenkoav 
App is getting crash when try to connect VPN, sharing u crash log txt file please check and help me out.

Thanks

[log.txt](https://github.com/AnchorFreePartner/hydrasdk-demo-android/files/6537900/log.txt)

**Comment by timoshenkoav** [comment]
Hello!
I see in logs crash in  /system/lib/libandroid_runtime.so, dont understand how is it related to the sdk. Please try to run on real device instead of emulator

**Comment by singhmeenu** [comment]
Hi,
Tested in real device, behaving same as 

Check logs and sharing your phone details

![Screenshot_2021-05-25-15-12-29-07](https://user-images.githubusercontent.com/26954063/119476702-ee2cdd00-bd6b-11eb-8d57-efb533894c2a.png)

[LOG.txt](https://github.com/AnchorFreePartner/hydrasdk-demo-android/files/6538252/LOG.txt)

**Comment by timoshenkoav** [comment]
#00 pc 000000000011f0c0  /system/lib64/libskia.so (_ZN8SkCanvas9drawColorEjN10SkXfermode4ModeE+72)
And again - its not releated to the sdk. try to build and run project from this repo without changes
