### ISSUE TITLE
App getting crash in Android 8 devices.

### ISSUE THREAD

**Issue by singhmeenu** [AnchorFreePartner/hydrasdk-demo-android#135]
Hi @timoshenkoav 
Sharing you logs. please check it and help me. 

[VPN logs.txt](https://github.com/AnchorFreePartner/hydrasdk-demo-android/files/6630516/VPN.logs.txt)

**Comment by timoshenkoav** [comment]
could you please also share the exact crash stack trace - or point to line number of log

**Comment by singhmeenu** [comment]
Hi @timoshenkoav 
there are two crashes which i found in Samsang J7 prime device android 8, sharing you both files 
 
[VPNapplog3.txt](https://github.com/AnchorFreePartner/hydrasdk-demo-android/files/6631062/VPNapplog3.txt)

[VPNapplog2.txt](https://github.com/AnchorFreePartner/hydrasdk-demo-android/files/6631078/VPNapplog2.txt)

**Comment by timoshenkoav** [comment]
3 - crash in the libhwui.so
2 - crash in IInputMethodManager 

Dont understand how are they related to the sdk.

**Comment by singhmeenu** [comment]
I checked demo app also but getting crash on that build , sharing you crash log please check this.


[demoapp.txt](https://github.com/AnchorFreePartner/hydrasdk-demo-android/files/6631530/demoapp.txt)

**Comment by timoshenkoav** [comment]
again, its crashing in libhwui.so (android::uirenderer::renderthread::CanvasContext::prepareAndDraw(android::uirenderer::RenderNode*)+174)

Its not related to sdk - its related to drawing system, and i cannot fix that
