### ISSUE TITLE
Not working in Bahrain, Saudi Arabia, and Dubai 

### ISSUE THREAD

**Issue by xpfasd** [AnchorFreePartner/hydrasdk-demo-android#14]
We tested demos in Bahrain, Saudi Arabia, and Dubai. We use demo but the login action will not succeed. HydraException is com.anchorfree .hydrasdk.exceptions.NetworkRelatedException: NetworkRelatedException , and our network is OK, access to other web pages is OK.
Our configuration information is as follows:
Key 8HCNSgPn3Z
URL https://backend.northghost.com/
I look forward to hearing from you soon

**Comment by timoshenkoav** [comment]
Hello!
Please try different url https://api-prod-partner-us-west-2.northghost.com/

**Comment by timoshenkoav** [comment]
also you can try this one https://d2isj403unfbyl.cloudfront.net

**Comment by xpfasd** [comment]
Thanks
https://d2isj403unfbyl.cloudfront.net is working!
