### ISSUE TITLE
Unable to upgrade plan

### ISSUE THREAD

**Issue by zaibniaz** [AnchorFreePartner/hydrasdk-demo-android#142]
I am trying to upgrade plan for last 4 hours and its keep on saying **"Your card has been declined."**

It takes inputs and ask for if u human or not after that it says **Your card has been declined.**

I have tried several cards but none worked.

**Comment by timoshenkoav** [comment]
@zaibniaz please email details to alexey@anchorfree.com

**Comment by zaibniaz** [comment]
@timoshenkoav please check your email.

**Comment by sufyan5008** [comment]
> @timoshenkoav please check your email.

can you please help me with these upgrading steps?
my email is sufyanhashmi23@gmail.com

**Comment by zohaib1sahni** [comment]
@timoshenkoav kindly mention the steps to upgrade the plan to the premium.
I cannot see any Billing or upgrade plan details on my console.
