### ISSUE TITLE
Carrier disabled

### ISSUE THREAD

**Issue by mentorbajrami** [AnchorFreePartner/hydrasdk-demo-android#147]
![Screenshot_20211110-043936_Gamers VPN](https://user-images.githubusercontent.com/63980912/141046121-14da30ef-a425-4cba-961f-ffde2d5b8a08.jpg)

I'm getting this error. I can access my carrier but this error shows when I open the app

**Comment by oxy9en** [comment]
Hi, 
we don't provide free VPN service more. 
Please send me an email to alexey@anchorfree.com for discussion.

**Comment by DeePsycho** [comment]
can you explain , 
what we need to do in that case?

**Comment by dharmiksit** [comment]
can you explain this error!
