### ISSUE TITLE
Target Version 31

### ISSUE THREAD

**Issue by Shvet** [AnchorFreePartner/hydrasdk-demo-android#149]
Hello,
I am trying to update my app with newest versions of SDKs and for that i need to increate my target version to 31 but your sdk is not optimize for target version 31. I would like to know if they are any update for this in near future?

**Comment by dharmiksit** [comment]
I Have the same problem.Please give fast solution

**Comment by Shvet** [comment]
Still waiting didnt get any reply.

**Comment by timoshenkoav** [comment]
sdk for target 31 is not ready yet.
