### ISSUE TITLE
What is Pricing of your service

### ISSUE THREAD

**Issue by nanashi1111** [AnchorFreePartner/hydrasdk-demo-android#15]
Hello, 

I have read this page https://developer.anchorfree.com/ and I couldn't find the part about your service pricing. I am considering using your service but I want to know the service price. Please help me know this.

Thank you.

**Comment by oxy9en** [comment]
we will public the pricing soon
but today it is free.

**Comment by karan1213** [comment]
What kind of limitation is been applied as free account?

**Comment by oxy9en** [comment]
No limitation now for free users but in future free users can use around 50Mb per day only.
