### ISSUE TITLE
Error when targeting S+ (version 31 and above)

### ISSUE THREAD

**Issue by kingmaf03** [AnchorFreePartner/hydrasdk-demo-android#150]
I got this error when trying to install it.

com.anchorfree.vpnsdk.vpnservice.AFVpnService: Targeting S+ (version 31 and above) requires that an explicit value for android:exported be defined when intent filters are present

**Comment by abenkdh** [comment]
add this to your manifest
`        <service
            android:name="com.anchorfree.vpnsdk.vpnservice.AFVpnService"
            android:enabled="@bool/vpn_process_enabled"
            android:permission="android.permission.BIND_VPN_SERVICE"
            android:process="@string/vpn_process_name"
            android:exported="false">
            <intent-filter>
                <action android:name="android.net.VpnService" />
            </intent-filter>
        </service>`

**Comment by kingmaf03** [comment]
Thanks @abenkdh . It works.
