### ISSUE TITLE
Could not find com.github.AnchorFreePartner.hydra-sdk-android:sdk:3.4.0.

### ISSUE THREAD

**Issue by shamimhossenbadol** [AnchorFreePartner/hydrasdk-demo-android#151]
Could not find com.github.AnchorFreePartner.hydra-sdk-android:sdk:3.4.0. issue in android studio version 7.0.4 and gradle version 7.0.2
please give me the solution so that I can use this vpn

**Comment by timoshenkoav** [comment]
what do you mean? Could you please specify the error?

**Comment by timoshenkoav** [comment]
Have you added jitpack as maven repo. Its described here https://auravpn.gitbook.io/paas/sdk/vpn-sdk-for-android
please read it carefully
