### ISSUE TITLE
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.

### ISSUE THREAD

**Issue by sufyan5008** [AnchorFreePartner/hydrasdk-demo-android#155]
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not find com.github.AnchorFreePartner.hydra-sdk-android:sdk:3.3.1.
     Required by:
         project :app
   > Could not find com.github.AnchorFreePartner.hydra-sdk-android:openvpn:3.3.1.
     Required by:
         project :app

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

**Comment by timoshenkoav** [comment]
update sdk to 3.6.2

**Comment by sufyan5008** [comment]
updated sdk to 3.6.2 but now servers are not showing in app
