### ISSUE TITLE
i getting webview issue 

### ISSUE THREAD

**Issue by Jaymin-Bhadani** [AnchorFreePartner/hydrasdk-demo-android#157]
Using WebView from more than one process at once with the same data directory is not supported. https://crbug.com/558377 : Current process com.test.test.test.test:my.custom.vpn

**Comment by timoshenkoav** [comment]
dont use webview from another process.

**Comment by Jaymin-Bhadani** [comment]
i requred for MobileAds.initialize(this);

**Comment by timoshenkoav** [comment]
if (ProcessUtils.isMainProcess(this)) {
            MobileAds.initialize(this);
}

**Comment by Jaymin-Bhadani** [comment]
thanks for helping it saved my day

**Comment by Jaymin-Bhadani** [comment]
can it same work for custom webview which i created in xml .?

**Comment by Jaymin-Bhadani** [comment]
application#onCreate

if (ProcessUtils.isMainProcess(this)) {
webView.loadUrl(Url);
}

like this .?

**Comment by timoshenkoav** [comment]
do you call webView.loadUrl(Url); inside application onCreate method? if so yes

**Comment by Jaymin-Bhadani** [comment]
yes in activity#oncreate
 on btn click to load privacy policy

**Comment by timoshenkoav** [comment]
so its not in application#onCreate method. so you dont need to do this check

**Comment by Jaymin-Bhadani** [comment]
thanks for helping
