### ISSUE TITLE
[HydraSdk.countries] callback is wrong!

### ISSUE THREAD

**Issue by xpfasd** [AnchorFreePartner/hydrasdk-demo-android#16]
hello!
I use hydrasdk-demo-android  ,everyting is ok. When [HydraSdk.countries]  is  success ,
the returned country information is wrong.For example, the country I finally connected to is the United States, but the return information is Germany.
Please fix it.
Thank you very much！

**Comment by oxy9en** [comment]
Hi,
can you send me the email with details of your situation? What is the IP of Germany server how you select the US. My email - alexey@anchorfree.com
Thanks
