### ISSUE TITLE
developer.anchorfree.com here is no option of signup / create new account. Then how to do it??

### ISSUE THREAD

**Issue by arslanarshad5254** [AnchorFreePartner/hydrasdk-demo-android#162]
developer.anchorfree.com here is no option of signup / create new account. Then how to do it??

**Comment by arslanarshad5254** [comment]
![image](https://user-images.githubusercontent.com/88225316/156423913-a1d7f966-c581-4935-b763-7a939f734bed.png)

**Comment by arslanarshad5254** [comment]
@timoshenkoav

**Comment by abdulawalarif** [comment]
You can browse this page and select your plan for signup.
https://www.aura.com/pricing

**Comment by Med-Foud** [comment]
> You can browse this page and select your plan for signup. https://www.aura.com/pricing

This is not Hydra SDK, This is a VPN Subscription for personal use !

**Comment by timoshenkoav** [comment]
please send information about your project to [alexey.skutin@aura.com](mailto:alexey.skutin@aura.com)
public registration is closed for now

**Comment by bhavin-qfonapp** [comment]
@timoshenkoav when it's gonna start again? you should at least provide information about this on https://developer.aura.com/
