### ISSUE TITLE
developer.anchorfree.com error 503 

### ISSUE THREAD

**Issue by Aarstudio1** [AnchorFreePartner/hydrasdk-demo-android#165]
I am watching from last 10 days developer.anchorfree.com website is showing 503 error code.  The devloper is also not giving any reply to the mail.  Are you all also facing the same problem?  If anyone has any solution please tell....
![Screenshot_20220328-081610~2](https://user-images.githubusercontent.com/96677084/160317975-d9b35887-05ba-49fc-bb10-c9e663790aab.png)

**Comment by Med-Foud** [comment]
Try this : https://developer.aura.com/
