### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by Jaymin-Bhadani** [AnchorFreePartner/hydrasdk-demo-android#166]
Caused by: org.gradle.internal.resolve.ArtifactResolveException: Could not download sdk-compat-3.6.2.aar (com.github.AnchorFreePartner.hydra-sdk-android:sdk-compat:3.6.2): No cached version available for offline mode

**Comment by Ashfaqpashtun** [comment]
try 3.6.1

**Comment by Jaymin-Bhadani** [comment]
Could not GET 'https://jitpack.io/com/github/AnchorFreePartner/hydra-sdk-android/openvpn/3.6.1/openvpn-3.6.1.aar'. Received status code 401 from server: Unauthorized

**Comment by Ashfaqpashtun** [comment]
file->invalid caches/Restart

**Comment by Ashfaqpashtun** [comment]
yes you are right now not working even clone demo also not working hope they provide solution @nikslushkin @timoshenkoav @igorglotov

**Comment by timoshenkoav** [comment]
should be fixed now. the problem is on jitpack side. We are working on moving from it to github packages or other service
