### ISSUE TITLE
The SDK will not work anymore?!

### ISSUE THREAD

**Issue by wecrtech** [AnchorFreePartner/hydrasdk-demo-android#168]
The SDK was amazing but now your website doesn't work and the SDK also doesn't work. Please let us know if you will stop supporting this SDK so we have to search for another one or search for another solution, please we have more than 20K daily active users using our app and we are using your SDK, and These issues are impacting our users and we keep losing more.

Please inform us if you are working on these issues or you already stopped supporting this SDK at all?

<img width="1568" alt="Screen Shot 2022-03-29 at 7 04 28 PM" src="https://user-images.githubusercontent.com/73659302/160671540-35cb4f87-8d99-490a-b263-8132262b2f5a.png">

**Comment by timoshenkoav** [comment]
Hello
use [developer.aura.com](http://developer.aura.com/) instead. sdk dependency should be fixed now
