### ISSUE TITLE
HydraSDK 2.2.3 is not built

### ISSUE THREAD

**Issue by samratsoul** [AnchorFreePartner/hydrasdk-demo-android#20]
Following code inside gradle is not working any more.

```

def hydra_version = "2.2.3"
implementation "com.github.AnchorFreePartner.hydra-sdk-android:sdk:$hydra_version"
```
I understand this is working for 2.3.0.   
Could you please let us know the exact reason why older (2.2.3) is not working.

**Comment by timoshenkoav** [comment]
It should work for 2.2.3 as well. Have you included jitpack repo in root level build.gradle? What is the error you get?

**Comment by timoshenkoav** [comment]
Why not to use last version? current last version is 2.4.0.

**Comment by samratsoul** [comment]
Due to some business reason i need to clarify why version 2.2.3 are not working. Otherwise i can not proceed.

version 2.2.3 stop working from yesterday.

This is the gradle build error from today:

```
ERROR: Unable to resolve dependency for ':app@debug/compileClasspath': Could not download hydratransport.aar (com.github.AnchorFreePartner.hydra-vpn-android:hydratransport:4ec8a84)
Affected Modules: app
```

Version from 2.3.0 built with no error. all below 2.3.0 are not working with this error.

**Comment by timoshenkoav** [comment]
Hello!
2.2.3 is not supported now. Current version is 2.4.1, please use it.
