### ISSUE TITLE
Duplicate class com.anchorfree.hydrasdk.rx.RxApiCallback

### ISSUE THREAD

**Issue by mercadeoshop** [AnchorFreePartner/hydrasdk-demo-android#21]
Hi, im receiving this error

Duplicate class com.anchorfree.hydrasdk.rx.RxApiCallback found in modules classes.jar (com.github.AnchorFreePartner.hydra-sdk-android:krakensdk:2.3.0) and classes.jar (com.github.AnchorFreePartner.hydra-sdk-android:rxsdk:2.3.0)
Duplicate class com.anchorfree.hydrasdk.rx.RxApiCompletableCallback found in modules classes.jar (com.github.AnchorFreePartner.hydra-sdk-android:krakensdk:2.3.0) and classes.jar (com.github.AnchorFreePartner.hydra-sdk-android:rxsdk:2.3.0)
Duplicate class com.anchorfree.hydrasdk.rx.RxCompletableCallback found in modules classes.jar (com.github.AnchorFreePartner.hydra-sdk-android:krakensdk:2.3.0) and classes.jar (com.github.AnchorFreePartner.hydra-sdk-android:rxsdk:2.3.0)
Duplicate class com.anchorfree.hydrasdk.rx.RxTrafficListener found in modules classes.jar (com.github.AnchorFreePartner.hydra-sdk-android:krakensdk:2.3.0) and classes.jar (com.github.AnchorFreePartner.hydra-sdk-android:rxsdk:2.3.0)
Duplicate class com.anchorfree.hydrasdk.rx.RxVpnStateListener found in modules classes.jar (com.github.AnchorFreePartner.hydra-sdk-android:krakensdk:2.3.0) and classes.jar (com.github.AnchorFreePartner.hydra-sdk-android:rxsdk:2.3.0)

**Comment by timoshenkoav** [comment]
Hi.
How do you add dependency in gradle?
It should be
 compile 'com.github.AnchorFreePartner.hydra-sdk-android:sdk:{VERSION_NAME}'
