### ISSUE TITLE
Some web sites can not unblocked

### ISSUE THREAD

**Issue by mwaked** [AnchorFreePartner/hydrasdk-demo-android#29]
VPN connection works but some web sites can not unblocked!
please help me because it is very important in my country,

Thanks

**Comment by timoshenkoav** [comment]
@mwaked what country and what websites? could you please provide additional information?

**Comment by mwaked** [comment]
in Qatar not work at all! @timoshenkoav

**Comment by timoshenkoav** [comment]
could you please share logs/exception

**Comment by mwaked** [comment]
It's keep give me this Exception in Qatar and some places in China:
Exception: VPNException: 182, Message: "Error in vpn service"

**Comment by timoshenkoav** [comment]
ok, thanks. can you please send all logs available?

**Comment by timoshenkoav** [comment]
also try to update to 3.1.0 sdk version

**Comment by timoshenkoav** [comment]
@mwaked also you can try with 3.1.0 version another transports openvpn-tcp/openvpn-udp. it supports automatic fallback

**Comment by mwaked** [comment]
@timoshenkoav Thanks a lot, it is work fine now after trying with 3.1.0 version another transports openvpn-tcp/openvpn-udp

**Comment by mwaked** [comment]
@timoshenkoav Thanks a lot, it is work fine now after trying with 3.1.0 version another transports openvpn-tcp/openvpn-udp
