### ISSUE TITLE
After upgrade hydra SDK from 0.28.5 to 1.0.1 I am getting crash

### ISSUE THREAD

**Issue by samratsoul** [AnchorFreePartner/hydrasdk-demo-android#3]
After upgrade hydra SDK from 0.28.5 to 1.0.1 I am getting following crash

`android.app.RemoteServiceException: can't deliver broadcast at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1802) at android.os.Handler.dispatchMessage(Handler.java:102) at android.os.Looper.loop(Looper.java:154) at android.app.ActivityThread.main(ActivityThread.java:6682) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)`

and this also:

`java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 916096 bytes at android.app.ContextImpl.sendBroadcast(ContextImpl.java:886) at android.content.ContextWrapper.sendBroadcast(ContextWrapper.java:421) at com.anchorfree.hydrasdk.SDKInitBroadcast$1.run(SDKInitBroadcast.java:88) at android.os.Handler.handleCallback(Handler.java:751) at android.os.Handler.dispatchMessage(Handler.java:95) at android.os.Looper.loop(Looper.java:154) at android.app.ActivityThread.main(ActivityThread.java:6247) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:892) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782) Caused by: android.os.TransactionTooLargeException: data parcel size 916096 bytes at android.os.BinderProxy.transactNative(Native Method) at android.os.BinderProxy.transact(Binder.java:615) at android.app.ActivityManagerProxy.broadcastIntent(ActivityManagerNative.j`

I could not found any root cause. Many device it is fine but for some of 7 device it causing crash in very high frequency

**Comment by timoshenkoav** [comment]
thanks for reporting, will fix and let you know the version with fix

**Comment by salaheddinegit** [comment]
same issue here

**Comment by timoshenkoav** [comment]
please update to latest sdk version just released - 2.2.1 and let me know if crash was fixed for you

**Comment by samratsoul** [comment]
Hello, We update Hydra library to 2.2.3 The above bug is fixed. But there was a new issue arise. This following bug is generating in very high frequency. It may be from your internal library. Please have a look and give us a suggestion.

java.lang.RuntimeException: Unable to create application com.sourcenext.wifisecurity.android.au.MainApplication: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 2 path $ at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5551) at android.app.ActivityThread.-wrap2(ActivityThread.java) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1576) at android.os.Handler.dispatchMessage(Handler.java:102) at android.os.Looper.loop(Looper.java:241) at android.app.ActivityThread.main(ActivityThread.java:6274) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 2 path $ at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226) at com.google.gson.Gson.fromJson(Gson.java:927) at com.google.gson.Gson.fromJson(Gson.java:892) at com.google.gson.Gson.fromJson(Gson.java:841) at com.google.gson.Gson.fromJson(Gson.java:813) at com.anchorfree.hydrasdk.RemoteConfigProvider.loadConfig(RemoteConfigProvider.java:101) at com.anchorfree.hydrasdk.CarrierBackend.<init>(CarrierBackend.java:94) at com.anchorfree.hydrasdk.CarrierSDK.<init>(CarrierSDK.java:51) at com.anchorfree.hydrasdk.HydraSdk.forCarrier(HydraSdk.java:1115) at com.anchorfree.hydrasdk.HydraSdk.internalInit(HydraSdk.java:356) at com.anchorfree.hydrasdk.HydraSdk.init(HydraSdk.java:233) at com.sourcenext.wifisecurity.android.au.MainApplication.initHydraSdk(MainApplication.java:80) at com.sourcenext.wifisecurity.android.au.MainApplication.onCreate(MainApplication.java:63) at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1025) at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5548) ... 8 more Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 2 path $ at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385) at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:215) ... 22 more

**Comment by timoshenkoav** [comment]
Hello!
Please update to version 2.3.1. Check documentation about migration
