### ISSUE TITLE
com.anchorfree.sdk.exceptions.InvalidTransportException: Transport was not set or found for call

### ISSUE THREAD

**Issue by mwaked** [AnchorFreePartner/hydrasdk-demo-android#30]
It keeps give me this exceptions:
com.anchorfree.sdk.exceptions.InvalidTransportException: Transport was not set or found for call

please help me!

**Comment by timoshenkoav** [comment]
Have you passed HydraTransport.TRANSPORT_ID to SessionConfig.Builder as per doc?
