### ISSUE TITLE
No response, No connection and No error after update version

### ISSUE THREAD

**Issue by mwaked** [AnchorFreePartner/hydrasdk-demo-android#33]
After update to last version i tried to connect but no response, no connection and no error, i don't now what happened,
please help me urgently

> private fun connect(forApps: ArrayList<String>) {
        val fallbackOrder: MutableList<String> = ArrayList()
        fallbackOrder.add(HydraTransport.TRANSPORT_ID)
        fallbackOrder.add(CaketubeTransport.TRANSPORT_ID_TCP)
        fallbackOrder.add(CaketubeTransport.TRANSPORT_ID_UDP)
        val bypassDomains: MutableList<String> = LinkedList()
        bypassDomains.add("*facebook.com")
        bypassDomains.add("*wtfismyip.com")
        UnifiedSDK.getInstance().vpn.start(SessionConfig.Builder()
                .withReason(TrackingConstants.GprReasons.M_UI)
                .withTransportFallback(fallbackOrder)
                .withTransport(CaketubeTransport.TRANSPORT_ID_TCP)
                .withVirtualLocation(selectedCountry)
                .forApps(forApps)
                .addDnsRule(TrafficRule.Builder.bypass().fromDomains(bypassDomains))
                .build(), object : CompletableCallback {
            override fun complete() {
                startUIUpdateTask()
            }
            override fun error(@NonNull e: VpnException) {
                updateUI()
                handleError(e)
            }
        })
    }

**Comment by timoshenkoav** [comment]
Hello!
Please provide logs, project id(carrier), and backend url used

**Comment by mwaked** [comment]
id(carrier): IkkXbYH6GS
backend url : https://d2isj403unfbyl.cloudfront.net

**Comment by timoshenkoav** [comment]
@mwaked any logs?

**Comment by mwaked** [comment]
See the problem is "getVpnState" not response, it dos't return any response no success or failure

> UnifiedSDK.getVpnState(object : Callback<VPNState> {
            override fun success(@NonNull state: VPNState) {
                if (state == VPNState.CONNECTED) {
                   //
                } else {
                  //
                }
            }

            override fun failure(@NonNull e: VpnException) {
                handleError(e)
            }
        })

**Comment by timoshenkoav** [comment]
Please send full adb logcat output

**Comment by mwaked** [comment]
Thanks, after update it is working fine
