### ISSUE TITLE
Some VOIP calls not working when VPN is connected

### ISSUE THREAD

**Issue by mwaked** [AnchorFreePartner/hydrasdk-demo-android#37]
I tried to make Facebook Messenger call in Kuwait country but it can not connected when VPN is connected,
Can you help me in this problem please?

     private fun connect() {
        val fallbackOrder: MutableList<String> = ArrayList()
        fallbackOrder.add(HydraTransport.TRANSPORT_ID)
        fallbackOrder.add(CaketubeTransport.TRANSPORT_ID_TCP)
        fallbackOrder.add(CaketubeTransport.TRANSPORT_ID_UDP)

        val bypassDomains: MutableList<String> = LinkedList()
        bypassDomains.add("*facebook.com")
        bypassDomains.add("*wtfismyip.com")
        UnifiedSDK.getInstance().vpn.start(SessionConfig.Builder()
                .withReason(TrackingConstants.GprReasons.M_UI)
                .withTransportFallback(fallbackOrder)
                .withTransport(HydraTransport.TRANSPORT_ID)
                .withVirtualLocation(selectedCountry)
                .addDnsRule(TrafficRule.Builder.bypass().fromDomains(bypassDomains))
                .build(), object : CompletableCallback {
            override fun complete() {
                startUIUpdateTask()
            }

            override fun error(@NonNull e: VpnException) {
                updateUI()
                handleError(e)
            }
        })
    }

**Comment by timoshenkoav** [comment]
Hello!
first try to remove bypass for facebook domain
bypassDomains.add("*facebook.com") - it was added just for sample

**Comment by mwaked** [comment]
@timoshenkoav Thanks i removed facebook domain, it's working fine now
