### ISSUE TITLE
IllegalArgumentException AFVpnService.onDestroy

### ISSUE THREAD

**Issue by StanKocken** [AnchorFreePartner/hydrasdk-demo-android#38]
We just updated our SDK to 3.1.2 to fix the crashes we had. And now we have even more crashes.

On the PlayStore we can see around 30 000 users impacted, after only one day of hotfix release, by the given crash:
<img width="737" alt="Screenshot 2020-03-20 at 10 20 28" src="https://user-images.githubusercontent.com/2204411/77150558-6f1b8500-6a94-11ea-8e77-208bb9aa45d1.png">

This crash seems to implicated all Android version (we have cases in Android 10, 9, 8, 7, 6), all manufacturers, but I'm not able to reproduce it in a dev environment.

**Comment by timoshenkoav** [comment]
thanks for the report

**Comment by StanKocken** [comment]
Any progress on this fix? Is it possible to have an ETA?
We have now over 50k users impacted.

**Comment by StanKocken** [comment]
Sorry, we have now 100k users impacted (more user impacted than users using the VPN normally).
We receive on those users a lot of `vpnStateChanged` to `IDLE` even if they are not using the VPN.

We still cannot reproduce it locally but it became a huge issue on side, please react to our messages.

**Comment by timoshenkoav** [comment]
hope to release new version this week

**Comment by StanKocken** [comment]
Thank you.
Can you precise me what is the potential impact on the bug you identified?
If you can help us giving steps to reproduce so we can identify better the potential on our live users today.

**Comment by timoshenkoav** [comment]
it happen if AFVpnService (child of android VpnService) onDestroy is called just after onCreate. Dont know the precise steps how to reproduce it

**Comment by StanKocken** [comment]
Given the number of cases per day, I suppose the service is even created even if it should not. As the user don't use it, it should even been started.

**Comment by timoshenkoav** [comment]
sdk version 3.1.2 has feature to disable starting the service. (now its started with app). Please check the docs

**Comment by timoshenkoav** [comment]
Hello
Version 3.2.0 released with crash fixed
