### ISSUE TITLE
Network timeout when connecting to backend.northghost.com

### ISSUE THREAD

**Issue by Mohamed-Hamed** [AnchorFreePartner/hydrasdk-demo-android#4]
I installed the android client sdk, and created an application at https://developer.anchorfree.com
When I try to authenticate a user anonymously, authentication fails due to the backend server timeout error.

The same error occurs while browsing the project at developer.anchorfree.com, the client fails to fetch my projects from backend.nortghost.com?access_token=xxxx due to network timeout, and I am signed out continously.

What can I do to solve this problem?
Knowing that the project dashboard works fine if I use a vpn client on my pc, meaning that the backend server is responding.

Is there a way to create my own custom backend server?

Thank you ..

**Comment by oxy9en** [comment]
Hi Mohamed-Hamed,

1) please check the project anonymous method. Open the project on the developer console, go to SETTINGS -> Auth method.
Do you see the anonymous method? If not, add the method:
name - "anonymous",
settings - "{}"
2) please check the login parameters in your app. You can see demo app for android - https://github.com/AnchorFreePartner/hydrasdk-demo-android
"carrier_id" = your project id

Regards

**Comment by Mohamed-Hamed** [comment]
Thank you oxy9en for your response,
Actually, I have already added the anonymous auth method as you mentioned, and sometimes authentication works.

But the problem is not related to project or client setup, It is that the address https://backend.northghost.com is not reachable most of the time, therefore I cannot access the project dashboard or authenticate users from the java client app because both of them rely on this backend server.

When I use a vpn on my pc I can access it normally, this makes the problem clear that it is related to my isp.

Any suggestions about this?
Thank you again...

**Comment by Mohamed-Hamed** [comment]
I managed to find a work around for backend server problem.
But now then I start vpn with optimal server the app freezes and virtual device reboots.
Any ideas ?

**Comment by Mohamed-Hamed** [comment]
I can now connect vpn service after moving the call to startVpn method to a background service
and debugging on an actual device not an emulator.

**Comment by Mohamed-Hamed** [comment]
The documentation of hydraVPN sdk starts with the following sentence:

> Android SDK is a part of Anchorfree Partner SDK which contains of client-side libraries and server-side applications needed to implement custom VPN infrastructure.

Where can I find these server-side applications needed to implement custom vpn infrastructure, and how can I integrate it with  my client code.

**Comment by oxy9en** [comment]
Hi,

_the address https://backend.northghost.com is not reachable most of the time_ - my recommendation use some cover like Amazon CloudFront for it.

_But now then I start vpn with optimal server the app freezes and virtual device reboots._ - no ideas. Does the demo app have the same issue?

_Where can I find these server-side applications needed to implement custom vpn infrastructure, and how can I integrate it with my client code._ - it means the SDK use our infrastructure and can't work without it.

**Comment by timoshenkoav** [comment]
there are some problems on emulators running vpn. Please try on real device. Its not required to move to startVPN call to background service

**Comment by Mohamed-Hamed** [comment]
@oxy9en 
The crash problem was solved, by using a real device as @timoshenkoav  recommended.
I'll try your recommendation for the backend server problem.
Thank you guys.

**Comment by xpfasd** [comment]
> I managed to find a work around for backend server problem.
> I can authenticate users successfully.
-------------------------------------------------------
I also met you with the same problem. How do you solve it?

**Comment by timoshenkoav** [comment]
what backend url do you use?

**Comment by Mohamed-Hamed** [comment]
> > I managed to find a work around for backend server problem.
> > I can authenticate users successfully.
> 
> I also met you with the same problem. How do you solve it?

I didn't do anything about it.
It just starting working.

**Comment by timoshenkoav** [comment]
@Mohamed-Hamed could you please try this backend url https://d2isj403unfbyl.cloudfront.net

**Comment by manserro** [comment]
https://backend.northghost.com  is blocked in UAE country. Am trying to build VPN app, but it keeps saying me: Please Login and list of countries doesnt popup. (I bought a script)

**Comment by timoshenkoav** [comment]
Hello!
Please try this url instead of backend... https://d2isj403unfbyl.cloudfront.net

**Comment by anas1991mohammad** [comment]
hello timoshenkoav ,
this url open for all country??

**Comment by timoshenkoav** [comment]
yes, it should be

**Comment by sufyanrasheedkhan** [comment]
hello, timoshenkoav I am facing a problem with the latest update 3.3.3 in the demo project it does not accept carrier id and show this toast "Error. check partner API exception constants" when a click the login button

**Comment by timoshenkoav** [comment]
please share the full error you see in logs

**Comment by sufyanrasheedkhan** [comment]
i have just extract and run the demo project  as it  is what changes do you recommend in the demo project

**Comment by timoshenkoav** [comment]
what is your carrier?

**Comment by sufyanrasheedkhan** [comment]
pakistan

**Comment by sufyanrasheedkhan** [comment]
2021-03-09 16:03:40.448 11512-11512/com.northghost.hydraclient W/MainActivity: PartnerApiException{code=200message=carrier_id field is invalid. please register project on https://developer.anchorfree.com/content=BAD_REQUEST}

**Comment by timoshenkoav** [comment]
there is no carrier specified in demo project. you need to create one

**Comment by timoshenkoav** [comment]
https://developer.anchorfree.com/signUp

**Comment by rajeevraghu** [comment]
@timoshenkoav :iam a beginner and when iam trying to signup using url:https://developer.anchorfree.com/signUp
it shows error :Internal server error, please try again,don't know why this is happening and I have tried several times.Could u pls provide me any solution for it???
