### ISSUE TITLE
Can't get current server after update config

### ISSUE THREAD

**Issue by tommydry** [AnchorFreePartner/hydrasdk-demo-android#41]
Hi!
I faced with a problem of getting info about current server after calling HydraSdk.updateConfig method.
After calling HydraSdk.updateConfig with a new virtualLocation there is no way to get a new server country name and server ip via CredentialsCompat.getServerIp(sessionInfo.credentials). It returns the same country name and ip that I connected before.
Edit:
But I can see from iplocation.com that my vpn config was updated!

**Comment by timoshenkoav** [comment]
Hello!
Thanks for the report
1. Please take into account migration to last version current is 3.2.0
2. will check if it reproduces on last version

**Comment by oxy9en** [comment]
@tommydry do you have any problems or I can close the Issue?
