### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by goldfish07** [AnchorFreePartner/hydrasdk-demo-android#43]
SDK version 3.3.0
E/USDK-RetryHelper: InternalRetry tag: login step:0 maxRetry: 3

**Comment by timoshenkoav** [comment]
what is this?

**Comment by goldfish07** [comment]
after using AnchorFreePartner service for 3 months, today suddenly i am getting login error in my application , i am unable to login. 
it seems AnchorFreePartner Server is rejecting my login request.

**Comment by timoshenkoav** [comment]
what is your carrier id and backend url?

**Comment by timoshenkoav** [comment]
also please specify sdk version

**Comment by goldfish07** [comment]
carrier id is VPN_CONNECT
backend url is https://backend.northghost.com
sdk version 3.2.0 tried is 3.3.0 too but still not work

**Comment by timoshenkoav** [comment]
what error do you get?

**Comment by haseebkamanger** [comment]
Same issue , Login Error.

**Comment by haseebkamanger** [comment]
@goldfish07 still having issue?

**Comment by haseebkamanger** [comment]
When try to login it shows :  Other error. Check RequestException Constants.

**Comment by timoshenkoav** [comment]
i can see some strange value for carrier_id - VPN_CONNECT, where is this from? Did you registered your project on https://developer.anchorfree.com/?

**Comment by goldfish07** [comment]
Yes i registered cause that carrier id works  for till yesterday after that
i was unable to login , then i create new account to check if issue in my
account, the new carrier id only works once than it never works again

**Comment by oxy9en** [comment]
@goldfish07  
try to reset password - https://developer.anchorfree.com/#/auth/reset
What email are you use for registration?

**Comment by goldfish07** [comment]
i am using email ayushbisht5663@gmail.com
project name is VPN_CONNECT

**Comment by oxy9en** [comment]
I send you email.

**Comment by HamzaImtiazMalik** [comment]
i am also getting the issue

**Comment by goldfish07** [comment]
@HamzaImtiazMalik  many people are facing this issue please wait, we are trying to solve this issue ASAP !
read this thread for Update ! :)

**Comment by goldfish07** [comment]
i tries using the sample project hydrasdk-demo-android
i was successfully logged in and to load countries and able to connect to server too,
but as soon as i changed the package name of  hydrasdk-demo-android , i again got login error.

**Comment by timoshenkoav** [comment]
@goldfish07 changing package name shouldn't affect connecting. just checked. could you please share logs

**Comment by goldfish07** [comment]
Error on request ApiRequest{url='https://backend.northghost.com/user/login', method='POST', body='{"result":"BAD_REQUEST","error |
E/USDK-NetworkCallback: | ":"carrier_id not found"}'} BAD_REQUEST                                                                                          |
2020-04-16 23:54:18.209 28310-28725/com.annsoft.vpn E/USDK-NetworkCallback: com.anchorfree.partner.exceptions.RequestException: Error on request ApiRequest{url='https://backend.northghost.com/user/login', method='POST', body='{"result":"BAD_REQUEST","error":"carrier_id not found"}'} BAD_REQUEST

**Comment by timoshenkoav** [comment]
so you also changed carrier id?

**Comment by goldfish07** [comment]
yes i created new project and added carrier id vpn_con this worked in demo app after changinf demo apps's package name it dosen't work anymore

**Comment by timoshenkoav** [comment]
so we return to previous problem

**Comment by goldfish07** [comment]
@timoshenkoav have Anchorfree backend team applied changes this week ? ,
the issue maybe in backend server not in Android apps!

**Comment by goldfish07** [comment]
@timoshenkoav it seems issue has been resolved , old carrier id working now !

**Comment by goldfish07** [comment]
the issue has been resolved now 
Thanks to @oxy9en and @timoshenkoav

**Comment by haseebkamanger** [comment]
What you do ?? @goldfish07 how fixed?

**Comment by innovationnow** [comment]
I am having the same issue, how to fix it? @timoshenkoav @goldfish07

**Comment by goldfish07** [comment]
@innovationnow  @haseebkamanger  create a new project new your account after that in location tab add all the countries , your carrier id will be your_company _code+project id  i.e full project id including company code you created while creating account

**Comment by innovationnow** [comment]
Thanks your solution worked, i didn't have to create new projects, i just updated the carried id (private key to project name) and added the locations as you mentioned

**Comment by haseebkamanger** [comment]
@innovationnow Please email me at hasiikamanger@gmail.com

**Comment by liaqateagle** [comment]
> @innovationnow @haseebkamanger create a new project in your account after that in location tab add all the countries , your carrier id will be your_company _code+project id i.e full project id including company code you created while creating account, may sure to confirm to test in both build type Release as well as debug

i not understand what u saying can you help me how to pick carrier id

**Comment by liaqateagle** [comment]
> Thanks your solution worked, i didn't have to create new projects, i just updated the carried id (private key to project name) and added the locations as you mentioned

can you share how you solve it

**Comment by liaqateagle** [comment]
@goldfish07  where we have to add countries ?

**Comment by innovationnow** [comment]
@liaqateagle  at network

**Comment by goldfish07** [comment]
/home/fish/Downloads/Screenshot_2020-04-17 AnchorFree Developer portal.png

**Comment by goldfish07** [comment]
![Screenshot_2020-04-17 AnchorFree Developer portal](https://user-images.githubusercontent.com/34901152/79571463-d8fd6d80-80d8-11ea-961e-80894b6caca7.png)

**Comment by liaqateagle** [comment]
Thanks Dear Issue Resolved

**Comment by anas1991mohammad** [comment]
i have same issue can any one help me

**Comment by liaqateagle** [comment]
> i have same issue can any one help me

yeah sur

**Comment by anas1991mohammad** [comment]
this link https://d2isj403unfbyl.cloudfront.net avilable in all country ??
because the backend.norghhost.com is not available in some country

**Comment by Humanbeing-bit** [comment]
I really don't understand about the your_company _code+project id
**Ex**: my company name: **startup** and my project id was **nocode_vpn** how do I put in the carrier id field 

Ex buildConfigField "String", "BASE_CARRIER_ID", "\"startup+nocode_vpn\""

Like this or its a wrong method

**Comment by goldfish07** [comment]
![Screenshot_2020-04-20 AnchorFree Developer portal](https://user-images.githubusercontent.com/34901152/79727842-a2a73480-830a-11ea-8677-e1e0fef1227c.png)

hello @Humanbeing-bit  ,
in above image you see project name Test , in which have below id 91_xyz123
when you created you anchorfree developer account , you have entered a company name and company code,  right !
so here in Test project company code is 91 and project id is xyz123, together we combine we got  a carrier id i.e 91_xyz123, 
make sure you to add countries in Network location tab
:*

**Comment by Humanbeing-bit** [comment]
@goldfish07 Thanks for the help

**Comment by s4suryapal** [comment]
This site not working : https://developer.anchorfree.com/

how to signup ?? I would like to integrate this SDK in my app, please help
