### ISSUE TITLE
Login Issue

### ISSUE THREAD

**Issue by haseebkamanger** [AnchorFreePartner/hydrasdk-demo-android#45]
When try to login it shows : Other error. Check RequestException Constants.

**Comment by timoshenkoav** [comment]
Hello. Please share logs. What is your carrier id?

**Comment by goldfish07** [comment]
please make this duplicate & close this issue we are discussing this in Thread #43

**Comment by haseebkamanger** [comment]
1233_melonvpn Carrier id

**Comment by goldfish07** [comment]
#43 check solution

**Comment by oxy9en** [comment]
@haseebkamanger do you have any problems or I can close this Issue?
