### ISSUE TITLE
all my apps are now giving error that carrier id not found I have registered on Anchor Free developer console

### ISSUE THREAD

**Issue by HamzaImtiazMalik** [AnchorFreePartner/hydrasdk-demo-android#46]

**Comment by oxy9en** [comment]
hi @HamzaImtiazMalik 
please go to https://developer.anchorfree.com/ and create the project (Public VPN) for your apps.
The project ID is the "carrier_id" for SDK.

**Comment by haseebkamanger** [comment]
I am using this email hasiikamanger@gmail.com still facing issue.

**Comment by goldfish07** [comment]
please close this issue and check thread #43
