### ISSUE TITLE
anchorfree developer 

### ISSUE THREAD

**Issue by anos19** [AnchorFreePartner/hydrasdk-demo-android#49]
hello guys 
i need link open all website and apps like calling whats app and Facebook messenger i need base host for all please

**Comment by goldfish07** [comment]
what you trying to say ?

**Comment by anas1991mohammad** [comment]
i try northhost.com  but it not available in some country and i try "https://d2isj403unfbyl.cloudfront.net but the connection is not compleated

**Comment by oxy9en** [comment]
try to open - https://d2isj403unfbyl.cloudfront.net/doc/all/index.html
if you see documentation, the URL works for you and the problem in your side.
