### ISSUE TITLE
 I am receiving Warning - this app does not meet Google Play permissions policy, even though my latest version doesn't require these permission?

### ISSUE THREAD

**Issue by salaheddinegit** [AnchorFreePartner/hydrasdk-demo-android#5]
**""This app does not meet the Google Play permissions policy relating to the use of SMS or CALL_LOG. You must fix this before March 9. 2019 or your app will be removed from Google Play. Note: if you have recently made a change, it can take up to 12 hours to update this message.
`""**

Indirectly means, may be any of the 3rd party library you are using in your project is already using those permissions. And when you build your project it merged all the Manifest file in a single Merged Manifest file. This is the reason you are getting this warning because your final manifest has any of those permission(s).

Please try to remove those permission from your SDK

**Comment by timoshenkoav** [comment]
Our sdk does not have such permissions. you can check this demo app resulting manifest to make sure, please check from where these permissions gets to your app with "ManifestMerge" tab in AndroidStudio

**Comment by salaheddinegit** [comment]
aah great, thank you for your response
