### ISSUE TITLE
anchor free developer 

### ISSUE THREAD

**Issue by anos19** [AnchorFreePartner/hydrasdk-demo-android#50]
hi guys  i need base url  to open from all country because the backend.northhost.com is not available from UAE and this base https://d2isj403unfbyl.cloudfront.net  is not open all blocked website

**Comment by timoshenkoav** [comment]
Hello!
Opening blocked websites does not depend on that url. With what websites do you have problems?

**Comment by anos19** [comment]
all calling app blocked and Porn sites

**Comment by timoshenkoav** [comment]
what is your sdk version?

**Comment by anos19** [comment]
2.4.1

**Comment by timoshenkoav** [comment]
please update to 3.3.0

**Comment by anos19** [comment]
but when i change to 3.3.0 the source code is have more problem

**Comment by anos19** [comment]
![Untitled](https://user-images.githubusercontent.com/62918812/80020315-798ccc80-84e1-11ea-87e6-933c50f85d27.png)

**Comment by timoshenkoav** [comment]
yes, its uncompatible change. you need to migrate

**Comment by anos19** [comment]
can you tell me how i can solve it after change sdk to 3.3.0

**Comment by timoshenkoav** [comment]
checkout the docs https://developer.anchorfree.com/#docs/all/unify_sdk_hydra__openvpn_for_android 
section about migration from 2.4.1 to 3.0.0

**Comment by anos19** [comment]
timoshenkoav  can you give me your email ??

**Comment by timoshenkoav** [comment]
a.timoshenko@anchorfree.com
