### ISSUE TITLE
com.anchorfree.partner.exceptions.NetworkException: java.net.UnknownHostException: backend.northghost.com

### ISSUE THREAD

**Issue by hashmih** [AnchorFreePartner/hydrasdk-demo-android#52]
Two days ago it was working fine but today when i connect it gives exception.

**Comment by timoshenkoav** [comment]
Hello!
Please try another url: https://d2isj403unfbyl.cloudfront.net

**Comment by hashmih** [comment]
Thankx for your support..it's working

**Comment by Shvet** [comment]
Same problem, It is now giving me same errors.

**Comment by timoshenkoav** [comment]
what is your device OS version?
