### ISSUE TITLE
Update 3.3.0 add 8MB to the build

### ISSUE THREAD

**Issue by StanKocken** [AnchorFreePartner/hydrasdk-demo-android#53]
Following the update of the SDK to the version 3.3.0, from 3.2.0, our build size increased drastically: +100% for the VPN size footprint.

This is due to the introduction of a new ".so" file called "libovpn3.so": 8MB. But also "libopenvpn" which is +1.4MB

Our list of ".so" files contains now (for the VPN):
libovpn3.so
libopenvpn.so
libopvpnutil.so
libhydra.so
libovpnexec.so

Why do we have this new "libovpn3.so"? Is it voluntary and is it meant to stay as is?

**Comment by timoshenkoav** [comment]
Hello!
Thanks for the report, you can exclude this file.

**Comment by StanKocken** [comment]
Thanks for the quick reply.
What do you mean I can exclude this file? It is provided directly by the SDK. Should I create a hack to remove this .so file at build time?

**Comment by timoshenkoav** [comment]
you can exclude it like this:
`
android { 
    packagingOptions {
        exclude 'lib/armeabi-v7a/libSomeLibYouDontWant.so'
    }
}
`

**Comment by StanKocken** [comment]
Thank for this.
But just to understand clearly, that's a library that should not be there and you will remove on your next update? Because it sounds weird for me that I have to do this while integrating your SDK.

**Comment by StanKocken** [comment]
I tested and it seems to work.
BTW I also tried to remove `libhydra.so`, as we use openvpn, and same the VPN seems working. Is there other "useless" .so files that I can remove to make our app lighter with this SDK?

**Comment by timoshenkoav** [comment]
if you use only openvpn you can exclude hydra from dependencies
replace 
`implementation 'com.github.AnchorFreePartner.hydra-sdk-android:sdk:{VERSION_NAME}'`
dependency to 
`implementation 'com.github.AnchorFreePartner.hydra-sdk-android:sdk-core:{VERSION_NAME}'`

**Comment by StanKocken** [comment]
You are right, I missed it from the documentation, it makes sense.
However, even with this sdk-core, I still have the same native librairies (including hydra).

**Comment by timoshenkoav** [comment]
Hello, @StanKocken!
Please use just released version 3.3.2
with this dependencies it does not include hydra.so
`
compile 'com.github.AnchorFreePartner.hydra-sdk-android:sdk-core:3.3.2'
compile 'com.github.AnchorFreePartner.hydra-sdk-android:openvpn:3.3.2'
`
