### ISSUE TITLE
release apk is not generated while debug apk is working

### ISSUE THREAD

**Issue by noshair** [AnchorFreePartner/hydrasdk-demo-android#55]
C:\Users\nosha\.gradle\caches\transforms-1\files-1.1\jetified-sdk-core-3.3.0.aar\4aa70cc5a09986cfd54aeff2932a7fa7\build\outputs\mapping\configuration.txt (The system cannot find the path specified)

**Comment by noshair** [comment]
build\outputs\mapping\configuration.txt  these folders are also not there i don't know how to configure

**Comment by timoshenkoav** [comment]
try to update gradle plugin. enable jettifier, do you use androidx?

**Comment by noshair** [comment]
Yes i am using andoridx
my main issue is 
\build\outputs\mapping\configuration.txt (The system cannot find the path specified) 
file is missing when i make release apk

**Comment by noshair** [comment]
i am using 3.3.0

**Comment by noshair** [comment]
i also saw that in directory i have only
C:\Users\nosha.gradle\caches\transforms-1\files-1.1\jetified-sdk-core-3.3.0.aar\4aa70cc5a09986cfd54aeff2932a7fa7
remaining folder is missing

**Comment by noshair** [comment]
if i make folders manually android studio delete it  when i make release apk

**Comment by noshair** [comment]
Problem is solved

**Comment by timoshenkoav** [comment]
could you please share details?
