### ISSUE TITLE
when i update 1.0to 3.3.0n app size increased from 11mb to 30 mb why?

### ISSUE THREAD

**Issue by noshair** [AnchorFreePartner/hydrasdk-demo-android#56]

**Comment by timoshenkoav** [comment]
1) added 64bits support
2) native library updates

**Comment by noshair** [comment]
implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.github.AnchorFreePartner.hydra-sdk-android:openvpn:3.3.0'
    implementation 'androidx.multidex:multidex:2.0.0'
    implementation 'com.github.AnchorFreePartner.hydra-sdk-android:sdk:3.3.0'
    implementation 'com.google.android.gms:play-services-ads:11.4.0'
    implementation 'com.crystal:crystalpreloaders:1.0.0'
    //noinspection GradleCompatible
    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'androidx.recyclerview:recyclerview:1.1.0'
    implementation 'com.jakewharton:butterknife:10.2.0'

    implementation 'com.github.bumptech.glide:glide:4.11.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.11.0'
    annotationProcessor 'com.jakewharton:butterknife-compiler:10.2.0'

**Comment by noshair** [comment]
Still  29mb

**Comment by noshair** [comment]
even android demo project is creating 30 mb release apk

**Comment by noshair** [comment]
ndk.abiFilters 'armeabi-v7a', 'arm64-v8a', 'x86', 'x86_64'
also added this line

**Comment by noshair** [comment]
exclude 'AndroidManifest.xml'
        exclude 'lib/armeabi-v7a/libovpn3.so'
        exclude 'lib/armeabi-v7a/libopenvpn.so'
        exclude 'lib/armeabi-v7a/libopvpnutil.so'
        exclude 'lib/armeabi-v7a/libhydra.so'
        exclude 'lib/armeabi-v7a/libovpnexec.so'

reduce6MB but still 24MB

**Comment by timoshenkoav** [comment]
is this a problem? you can analyse apk and check what was changed

**Comment by timoshenkoav** [comment]
btw 1.0 did not have x86_64 and arm64-v8a

**Comment by noshair** [comment]
I build aab and it and upload  it converts  into small automatically
