### ISSUE TITLE
Jvm Target 1.6 Kotlin 

### ISSUE THREAD

**Issue by AdilSattar1233** [AnchorFreePartner/hydrasdk-demo-android#57]
I am facing issue on kotlin project. Kindly resolve this issue.
Error: 
Calls to static methods in Java interfaces are prohibited in JVM target 1.6. Recompile with '-jvm-target 1.8'

**Comment by timoshenkoav** [comment]
so solve this either change kotlin prefs to compile with jvm target 1.8, or create java wrapper class with static methods to call interface static methods, and use it from kotlin
