### ISSUE TITLE
Android 8 notification not showing up, ActivityThread throws RemoteServiceException

### ISSUE THREAD

**Issue by salaheddinegit** [AnchorFreePartner/hydrasdk-demo-android#6]
In the Developer console it shows me, that this error only exists on Android 8 and it is showy often on Xperia Devices... This doesn't match to the distribution of the app over devices / Android versions..... At this time, I have no idea how to handle this problem. Maybee it is related to some special cases or combinations of devices and Android 8. And this is my Main Code to show the notification PS ( ALREADY TRY SVG/PNG/ ALL SIZES) same problem

old version of your code  
`@Override
public void onCreate() {
    super.onCreate();

    api = AFClientService.newBuilder(this)
            .setCarrierId("*****")
            .setHostUrl("********************")
            .setVPNNotificationProvider(new VPNNotificationProvider() {
                // NOTE: this method will be called from VPN process, reference to MainApplication will be different
                @Override
                public Notification createVPNNotification(String message, String ticker, boolean b, long l, VpnStatus.ConnectionStatus connectionStatus) {
                    return new NotificationCompat.Builder(getApplicationContext(), "*****")
                            .setContentText(message)
                            .setTicker(ticker)
                            .setContentTitle("**********")
                            .setSmallIcon(R.drawable.ic_notification)
                            .build();
                }
            })
            .build();
}
public AFClientService getApi() {
    return api;
}`

**Comment by timoshenkoav** [comment]
Hi,
As i understood its from caketube sdk. What is your sdk version? Do you use correct channel id?

**Comment by salaheddinegit** [comment]
Hi timoshenkoav 
compileSdkVersion 28

i don't know how to, can you help with that please ? 

thank you

**Comment by timoshenkoav** [comment]
you need to follow this doc to create channel
https://developer.android.com/training/notify-user/channels#CreateChannel
and then pass your channel id to new NotificationCompat.Builder(getApplicationContext(), "*****")

**Comment by salaheddinegit** [comment]
i will, thank you
if anything you can help me with please do, in your code you are already using a VPNNotificationRovider and that AFClientService to return api, a got some errors trying to fix that because this AFClientService is all over in MainActivity class.

i will read over and over the documentation, and thank you for your amazing work keep going

**Comment by timoshenkoav** [comment]
how are things going? was you able to show notification? Any other issues?

**Comment by salaheddinegit** [comment]
Hi 
not yet, seems like in the MainApplication you are using  api AFClientService to connect to the server,i don't know the proper way to change it.
wish you help me just to disable that notification or modify it without using that caketub or VPNNotificationProvider

**Comment by timoshenkoav** [comment]
not sure i understand your problem. Could you please provider more details

**Comment by salaheddinegit** [comment]
this method to show notification crashing in android 8, tried to not use notification at all, and there for the connectivity is not done, how can i change it without changing the hole application.  this is your old version of code. you are have all the details and you understant every part of it

and i wish i can thank you for your amazing work otherwise, your application is a masterpiece

**Comment by salaheddinegit** [comment]
Hi
i want to use your new code with ur sdk, seems Like your last updates work great, but want to ask you how can i make some changes for exemple, logging directly  without having that button "afdemo" login logout, and how can i name the countries with their full name, for examle "fr" = "france"  ?

**Comment by timoshenkoav** [comment]
hi, sory for the delay. to get full country name you can use 
Locale loc = new Locale("",country);
return loc.getDisplayCountry();

Another part of message i dont understand what changes do you need.
