### ISSUE TITLE
Q- How i can know if the current connected VPN is OPTIMAL _SERVER Or not?

### ISSUE THREAD

**Issue by mwaked** [AnchorFreePartner/hydrasdk-demo-android#60]
Hello,
i hope all is well, i have a question...

Q- How i can know if the current connected VPN is OPTIMAL _SERVER Or not?

I need to update the ui after user close the app and open it again i want to check  if the current connected VPN is OPTIMAL _SERVER Or not?
And  `UnifiedSDK.COUNTRY_OPTIMAL` always is empty

Thanks

**Comment by timoshenkoav** [comment]
you can save this information on app level if the last connection was to optimal server.

**Comment by mwaked** [comment]
@timoshenkoav I tried this solution but it dos't work with me, once i close the app the values in the application class reset to the default values!

**Comment by timoshenkoav** [comment]
so store they in sharedpreferences
