### ISSUE TITLE
Is there any way to block list of domains when VPN is connected?

### ISSUE THREAD

**Issue by mwaked** [AnchorFreePartner/hydrasdk-demo-android#61]
Hello,
I hope all is well, i have a small question,
can i block some domains by using **hydrasdk** when VPN is connected??

Thanks

**Comment by timoshenkoav** [comment]
Hello!
Checkout docs section
Categorization service (aka Fireshield) (Hydra transport only)

**Comment by mwaked** [comment]
@timoshenkoav Can you please send me the link to **Categorization service**, i cant find it

**Comment by timoshenkoav** [comment]
https://developer.anchorfree.com/#docs/all/unify_sdk_hydra__openvpn_for_android
