### ISSUE TITLE
When I Upgraded SDK Version to 3.3.1, Causing Errors in Main Activity

### ISSUE THREAD

**Issue by PratapKumarChowdary** [AnchorFreePartner/hydrasdk-demo-android#64]
implementation 'com.github.AnchorFreePartner.hydra-sdk-android:sdk:2.2.0'

When i Use Above (My Old) SDK Version , My Main Activity Doesn't Show any errors,

But implementation 'com.github.AnchorFreePartner.hydra-sdk-android:sdk:3.3.1'
When I Changed it to 3.3.1, 

In [MainActivity] Show Errors in Import Statements

import android.util.Log;
import com.anchorfree.hydrasdk.HydraSdk;
import com.anchorfree.hydrasdk.SessionConfig.Builder;
import com.anchorfree.hydrasdk.SessionInfo;
import com.anchorfree.hydrasdk.api.AuthMethod;
import com.anchorfree.hydrasdk.api.data.Country;
import com.anchorfree.hydrasdk.api.data.ServerCredentials;
import com.anchorfree.hydrasdk.api.response.RemainingTraffic;
import com.anchorfree.hydrasdk.api.response.User;
import com.anchorfree.hydrasdk.callbacks.Callback;
import com.anchorfree.hydrasdk.callbacks.CompletableCallback;
import com.anchorfree.hydrasdk.callbacks.TrafficListener;
import com.anchorfree.hydrasdk.callbacks.VpnStateListener;
import com.anchorfree.hydrasdk.compat.CredentialsCompat;
import com.anchorfree.hydrasdk.dns.DnsRule;
import com.anchorfree.hydrasdk.exceptions.ApiException;
import com.anchorfree.hydrasdk.exceptions.ApiHydraException;
import com.anchorfree.hydrasdk.exceptions.HydraException;
import com.anchorfree.hydrasdk.exceptions.NetworkRelatedException;
import com.anchorfree.hydrasdk.exceptions.VPNException;
import com.anchorfree.hydrasdk.vpnservice.VPNState;
import com.anchorfree.reporting.TrackingConstants.GprReasons;

Show Above are UnUsed Import Statements, How to Fix It

**Comment by timoshenkoav** [comment]
Hello!
version 3.* has uncompatible changes when updating from 2.*. please check 
**SDK version migration** section with 2.4.1 - 3.0.0 on the doc
https://developer.anchorfree.com/#docs/all/unify_sdk_hydra__openvpn_for_android
