### ISSUE TITLE
implementation problem

### ISSUE THREAD

**Issue by mjjisan** [AnchorFreePartner/hydrasdk-demo-android#67]
ERROR: Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve com.github.AnchorFreePartner.hydra-sdk-android:sdk:3.2.0.
Show Details
Affected Modules: app

**Comment by timoshenkoav** [comment]
Please try again. there was jitpack down

**Comment by mjjisan** [comment]
it's worked, thanks for your kind information...

**Comment by ifaisal2424** [comment]
Could not GET 'https://jitpack.io/com/github/AnchorFreePartner/ucr-analytics-android/3.1.9/ucr-analytics-android-3.1.9.pom'

i get these error any solution?
