### ISSUE TITLE
Not working in dubai

### ISSUE THREAD

**Issue by haseebkamanger** [AnchorFreePartner/hydrasdk-demo-android#7]
Unable to connect with any server.

**Comment by timoshenkoav** [comment]
Was you able to solve the issue. Please provide more details so we can get deeper on this

**Comment by haseebkamanger** [comment]
May be Ips are banned in dubai , un able to connect in dubai. please check
your sample sdk apk in dubai.

**Comment by timoshenkoav** [comment]
what is you carrier/backend url?

**Comment by timoshenkoav** [comment]
could you please try this backend url https://d2isj403unfbyl.cloudfront.net

**Comment by mwaked** [comment]
@timoshenkoav this https://d2isj403unfbyl.cloudfront.net it is work in Dubi but in Qatar it is give me error in transport

**Comment by timoshenkoav** [comment]
@mwaked what error do you get?
