### ISSUE TITLE
Get Connection Status when application is in background.

### ISSUE THREAD

**Issue by zohaib1sahni** [AnchorFreePartner/hydrasdk-demo-android#70]
I want to get connection status when app is running in background..like Connection duration and vpn status..is their any method in sdk or i've to make my own service for getting connection stats..?

**Comment by timoshenkoav** [comment]
to get vpn status - UnifiedSDK.getVpnState
to get connection duration - UnifiedSDK.getInstance().getVPN().getStartTimestamp

**Comment by zohaib1sahni** [comment]
Thanks..
