### ISSUE TITLE
Not Working in Saudi Arabia

### ISSUE THREAD

**Issue by arrafi23** [AnchorFreePartner/hydrasdk-demo-android#73]
Hi @timoshenkoav 
When i try 1st time Servers not showing in Arabic country. After that when i try with "https://d2isj403unfbyl.cloudfront.net" this Base url it's work fine in dubai and related country but it's not working in Saudi Arabia. Can you please give me salutations? Please reply my Issues as soon as possible.
Thank You

**Comment by oxy9en** [comment]
Hi @arrafi23 

looks like this URL blocked in Saudi Arabia. 
You can try to create another proxy Cloudfront URL - [https://pango.gitbook.io/pango-platform/resources/how-to/aws-cloudfront-distribution](https://pango.gitbook.io/pango-platform/resources/how-to/aws-cloudfront-distribution)
or try to do it in MS Azure or other services.

**Comment by arrafi23** [comment]
Thank you @oxy9en 
Let me check it.

**Comment by arrafi23** [comment]
Hi @oxy9en 
I'm check it but for this i need AWS Account. But I don't have any international card for pay 1usd. Can you please generate a link for me?

**Comment by oxy9en** [comment]
Try to use it - d1nexf8vxmu4h9.cloudfront.net

**Comment by arrafi23** [comment]
Thank you letme try it and let you know it work or not

**Comment by razmjooDev** [comment]
I have the same problem in Iran

**Comment by arrafi23** [comment]
@oxy9en Not working can you please provide any other solutation?

**Comment by arrafi23** [comment]
> I have the same problem in Iran

Did you find any solutation?

**Comment by razmjooDev** [comment]
> > I have the same problem in Iran
> 
> Did you find any solutation?

Not yet . He said in version 3.3.2 that he has solved this problem but this problem still persists

**Comment by timoshenkoav** [comment]
Hello!
Could you please check comments on this issue https://github.com/AnchorFreePartner/hydrasdk-demo-android/issues/82
