### ISSUE TITLE
SSL handshake timed out

### ISSUE THREAD

**Issue by razmjooDev** [AnchorFreePartner/hydrasdk-demo-android#74]
hi 
when I use cloudfront get SSL handshake timed out in some device 
please help me to fix it

**Comment by timoshenkoav** [comment]
@razmjooDev with what devices do you have this issue? android version?

**Comment by razmjooDev** [comment]
In almost all versions. Works on Android 10 on one phone but not on another. My guess is that it is from my country's internet. IRI

**Comment by timoshenkoav** [comment]
Hey, want to clarify if there any progress on this? What is your sdk version, url used?

**Comment by timoshenkoav** [comment]
@razmjooDev any update?

**Comment by razmjooDev** [comment]
I migrated to the last update but it did not work again
The solution I found was to set the certificate for SSL and change it on android: networkSecurityConfig
