### ISSUE TITLE
Implementation issue

### ISSUE THREAD

**Issue by ifaisal2424** [AnchorFreePartner/hydrasdk-demo-android#75]
Could not GET 'https://jitpack.io/com/github/AnchorFreePartner/ucr-analytics-android/3.1.9/ucr-analytics-android-3.1.9.pom'

i get these error any solution?

**Comment by timoshenkoav** [comment]
Hello,
Try now. seems like jitpack issue

**Comment by ifaisal2424** [comment]
I have try full day but issue not solved please help me with some extra
details how can I solve it thanks

**Comment by timoshenkoav** [comment]
now if i click the link you provided it opens correctly.

**Comment by ifaisal2424** [comment]
ok thanks
