### ISSUE TITLE
 server connection problem using chrome browser

### ISSUE THREAD

**Issue by Dev-Globalsoft7** [AnchorFreePartner/hydrasdk-demo-android#78]
maximum users reporting server not connection still loading sometime showing refuse to connect please fix it

**Comment by timoshenkoav** [comment]
Hello.
Could you please share server addresses you have problems with?

**Comment by Dev-Globalsoft7** [comment]
France, Germany, Italy, UK, USA etc. servers when I connected in mobile chrome browser said "connection refused" and like as when VPN connected to google.com in Chrome Android

**Comment by Dev-Globalsoft7** [comment]
today i cant login my admin panel too, after login its kicking me out again login page

**Comment by timoshenkoav** [comment]
Hello!
The issue should be fixed now
