### ISSUE TITLE
Servers loading but if connected on any server users not connect on any websites or apps?

### ISSUE THREAD

**Issue by beratsenv** [AnchorFreePartner/hydrasdk-demo-android#79]
Hello,  a lot users not connect any websites while vpn is opened?
Also, in my developer page user's countries showing "xx" location and getting lazy loading VPN countries?
If there any problem on servers? 
Thanks for your interesting....

**Comment by timoshenkoav** [comment]
Hello.
Could you please share server addresses you have problems with?

**Comment by beratsenv** [comment]
Hello, 500_ninja this is my pango developer project id.

https://imgur.com/a/aDZReKm
I have problem with France, Germany, Italy servers when I connected in mobile chrome browser said "connection refused"
And as you see my users' location "xx" problem.

**Comment by skahmed212** [comment]
> 
> 
> Hello, 500_ninja this is my pango developer project id.
> 
> https://imgur.com/a/aDZReKm
> I have problem with France, Germany, Italy, UK, USA etc. servers when I connected in mobile chrome browser said "connection refused" and like as when VPN connected write google.com in Chrome Android / seems wi-fi not working on chrome.. and not get a results.
> And as you see my users' location "xx" problem.
> 
> They started showing like this at night.
> 
> @timoshenkoav

im also facing same problem from last 2-3 days

**Comment by Dev-Globalsoft7** [comment]
@beratsenv

**Comment by timoshenkoav** [comment]
Hello!
The issue should be resolved now @Dev-Globalsoft7 @beratsenv 
'XX' has users that was not possible to detect the source country by geoip database, we will check the reason.
