### ISSUE TITLE
unable to block few domains

### ISSUE THREAD

**Issue by bazilbycom** [AnchorFreePartner/hydrasdk-demo-android#80]
UnifiedSDK.getInstance().getVPN().start(new SessionConfig.Builder()                
        .withReason(TrackingConstants.GprReasons.M_UI)                             
        .withTransportFallback(fallbackOrder)                                      
        .withVirtualLocation(selectedCountry)                                      
        .withTransport(HydraTransport.TRANSPORT_ID)                                
              .addProxyRule(TrafficRule.Builder.block().fromAssets("adblock.txt"))       
             .addDnsRule(TrafficRule.Builder.block().fromAssets("adblock.txt"))        
        .build(), new CompletableCallback() {   

i tried adding both proxyrule as well as dns rule. 
and ablock.txt has just 3 domains
127.0.0.1 indishare.org
127.0.0.1 googleadservices.com
127.0.0.1 googleads.g.doubleclick.net

Nothing works

**Comment by timoshenkoav** [comment]
Hello!
File should contain just domains

indishare.org
googleadservices.com
googleads.g.doubleclick.net

**Comment by timoshenkoav** [comment]
@bazilbycom any update?

**Comment by bazilbycom** [comment]
Let me try it.

**Comment by timoshenkoav** [comment]
@bazilbycom any news?
