### ISSUE TITLE
again server problem bro  not connecting , first turkey , uae then now india 

### ISSUE THREAD

**Issue by Dev-Globalsoft7** [AnchorFreePartner/hydrasdk-demo-android#82]
please fix sir asap , getting down my apps rating , atleast i want india country as proper works , lots of user from india country , please please fix sir

**Comment by beratsenv** [comment]
Same i updated sdk version with latest but India users not connecting anymore please check it out your sdk

**Comment by timoshenkoav** [comment]
Hello, please provide logs/error you have so i can investigate. I am not in these countries

**Comment by beratsenv** [comment]
I'm not here on India too but my users' feedback not downloading server list anymore ( i don't understand 30.000 indian users not connecting anymore why i think government problem blocked your api  link)

**Comment by beratsenv** [comment]
Also I'm researching for news not connect another vpn anymore India, so everything okey in my country but I don't here i don't get any logs or error anymore because firebase don't catch any problem for this issue

**Comment by beratsenv** [comment]
Do you have any solution for this issue?

@timoshenkoav

**Comment by timoshenkoav** [comment]
Hello,
You can try to use different url.
Last sdk version can rotate and try different urls.
try to define these:
https://z2v0lwnhcnrlci51cwo.get-carter.us/
https://awebhtpo3u8g5t.ecoweb-network.com
https://d1nexf8vxmu4h9.cloudfront.net

Try to create new URL
https://pango.gitbook.io/pango-platform/resources/how-to/aws-cloudfront-distribution

**Comment by beratsenv** [comment]
> Hello,
> You can try to use different url.
> Last sdk version can rotate and try different urls.
> try to define these:
> https://z2v0lwnhcnrlci51cwo.get-carter.us/
> https://awebhtpo3u8g5t.ecoweb-network.com
> https://d1nexf8vxmu4h9.cloudfront.net
> 
> Try to create new URL
> https://pango.gitbook.io/pango-platform/resources/how-to/aws-cloudfront-distribution


I updated my SDK version  2.4 to 3.3.2 latest 
seems working good. But I am putting new link on this area am I right?


> "     buildConfigField "String", "BASE_HOST", "\"https://awebhtpo3u8g5t.ecoweb-network.com\""

**Comment by timoshenkoav** [comment]
you can define only 1 url there. Use ClientInfo.newBuilder.addUrls to add multiple urls to your config

**Comment by beratsenv** [comment]
Do you have any example for multiple configs entegration?

How to implament as arraylist or with arrays.xml?


>   ClientInfo clientInfo = ClientInfo.newBuilder()
                .addUrls("")
                .baseUrl(prefs.getString(BuildConfig.STORED_HOST_URL_KEY, BuildConfig.BASE_HOST))
                .carrierId(prefs.getString(BuildConfig.STORED_CARRIER_ID_KEY, BuildConfig.BASE_CARRIER_ID))
                .build();
        unifiedSDK = UnifiedSDK.getInstance(clientInfo);
        updateVPN();

**Comment by beratsenv** [comment]
Ok. I write a code part

Can you check it out please?

>         createNotificationChannel();
>         List<String> urls = Lists.newArrayList("https://d1nexf8vxmu4h9.cloudfront.net", "https://z2v0lwnhcnrlci51cwo.get-carter.us/","another one aws link..");
>         SharedPreferences prefs = m_home_instance.getSharedPreferences(BuildConfig.SHARED_PREFS, Context.MODE_PRIVATE);
>         ClientInfo clientInfo = ClientInfo.newBuilder()
>                 .addUrls(urls)
>                 .baseUrl(prefs.getString(BuildConfig.STORED_HOST_URL_KEY, BuildConfig.BASE_HOST))
>                 .carrierId(prefs.getString(BuildConfig.STORED_CARRIER_ID_KEY, BuildConfig.BASE_CARRIER_ID))
>                 .build();
>         unifiedSDK = UnifiedSDK.getInstance(clientInfo);
>         updateVPN();

**Comment by beratsenv** [comment]
>   public static final String STORED_CARRIER_ID_KEY = "com.northghost.afvclient.CARRIER_ID_KEY";
>   public static final String STORED_HOST_URL_KEY = "com.northghost.afvclient.STORED_HOST_KEY";

> 
>   ClientInfo clientInfo = ClientInfo.newBuilder()
>                 .addUrls(urls)
>                 .baseUrl(prefs.getString(**BuildConfig.STORED_HOST_URL_KEY**, BuildConfig.BASE_HOST))
>                 .carrierId(prefs.getString(**BuildConfig.STORED_CARRIER_ID_KEY**, BuildConfig.BASE_CARRIER_ID))
>                 .build();

for example if goverment blocked northost domain, by the way what happaned on buildconfig urls?

**Comment by timoshenkoav** [comment]
1. you should not use northghost domain.
2. you can remove baseUrl url. Just use addUrls instead

**Comment by beratsenv** [comment]
Ok so a lot thanks!!!

One more question:
in sdk what happen carriedID? so include nortghost.com domain

What can I do?


 ClientInfo clientInfo = ClientInfo.newBuilder()
            .addUrls(urls)
            **.carrierId(prefs.getString(BuildConfig.STORED_CARRIER_ID_KEY, BuildConfig.BASE_CARRIER_ID))**
            .build();

**Comment by timoshenkoav** [comment]
as carrierId you should set you project id from dashboard - nothing changes

**Comment by beratsenv** [comment]
> as carrierId you should set you project id from dashboard - nothing changes

Thanks a lot for your good services
A lot of thanks....
