### ISSUE TITLE
Getting error when I click on Connect PartnerApiException{code=403message=nullcontent=TRAFFIC_EXCEED}

### ISSUE THREAD

**Issue by brjichkar** [AnchorFreePartner/hydrasdk-demo-android#88]
I was able to successfully run the code since last 4 days and all of sudden since 1 hour I am having this issue.
I am able to login, but when I click on connect , i get following exception. 

com.anchorfree.vpnsdk.exceptions.TrackableException: PartnerApiException{code=403message=nullcontent=TRAFFIC_EXCEED}

**Comment by timoshenkoav** [comment]
Hello. So you have exceeded you traffic limit of 50mb.

**Comment by brjichkar** [comment]
Ok thanks. It will be get reset tomorrow again right?

**Comment by timoshenkoav** [comment]
yes, it should

**Comment by brjichkar** [comment]
Is there any way we can remove 50 MB limit? I will be very thankful if you can point me in right direction.

**Comment by timoshenkoav** [comment]
https://pango.gitbook.io/pango-platform/console-details/project-settings/user-payment-methods

**Comment by brjichkar** [comment]
thanks a lot man.

**Comment by nikslushkin** [comment]
In upcoming updates of our platform, we will start to charge a fee for every monthly active unlimited user.
If you have any questions regarding our unlimited service please contact me by email partnership@pango.co

**Comment by RaufJavid** [comment]
I am asking this question in the Android App Scenario...How developers have to Pay Per Project?

Do they just Add Payment Details in the Developer Avchor Free Admin Panel while creating the project like "$3 per month for unlimited user" plan?

Or there is another way for Unlimited pLan...I am confused about how your Payment Plan works?

Is this way it works: 

I created the Project in AnchorFree, Selected a $3 Per Month Unlimited Users Plan...After that Added Credit Card Details...Now users using the app have no traffic limit.

Or there is anything else I have to do?

**Comment by noshair** [comment]
And i think if there is payment method in every user app then our users will be lost and they use other free vpns which is big loss for your follower developers

**Comment by Humanbeing-bit** [comment]
how can we buy custom Plan? I don't see any payment option

**Comment by abdullah-malabar** [comment]
I see a custom subscription. after enter credit card, I do not get this option. how can we buy custom plan?
