### ISSUE TITLE
Limited Bandwidth

### ISSUE THREAD

**Issue by inabdev30** [AnchorFreePartner/hydrasdk-demo-android#89]
VPN unable to connect after 50mb data usage. I am also unable to change the default bandwidth limit from the portal. Please tell me how I can increase the limit and how I can set bandwidth limit programmatically unable to find any option related to this in the documentation also.

Currently, I am using Hydra SDK for android.

Thanks.

**Comment by nikslushkin** [comment]
Please check similar issue: #88

**Comment by inabdev30** [comment]
I have checked that issue, don't you think 50mb is too low? is 50mb is the max data limit user can use for free or we can increase it because currently, the default bandwidth filed is uneditable and if the adding payment method is the only solution then what are the available subscriptions user can choose from?

**Comment by nikslushkin** [comment]
Hi @inabdev30 . Thanks for asking. 
We are discussing in the team other plans to provide more limited bandwidth for less price. For now, we can offer only 50mb limit for free users.
 
We can talk about custom terms of service for you and I can configure your project manually. Please send me an email with your project id and link to the application if it is available to partnership@pango.co.

**Comment by inabdev30** [comment]
Thank you so much for providing me with a custom plan option, But can you tell when anchor free is going to update the admin panel so, that every user can choose the desired subscription?

**Comment by RaufJavid** [comment]
I think there free plan is not very good...They need to change it. Are you kidding with a free 50MB Limit? You need to increase it.

**Comment by inabdev30** [comment]
@nikslushkin @timoshenkoav So, what charges your team has decides i just checked my admin panel and i get premium service option which is "$3 per MAU". This means i have to pay $3 per user. So, if i have 1K users then i have to pay $3K to you? Please explain it.

**Comment by nikslushkin** [comment]
Hi @inabdev30 ! Thanks for asking.
First of all, the price is for each UNLIMITED / PREMIUM active user. 
Let me explain the current flow:
- Your app offers a subscription to a user (Google Play or Huawei Store)
- User pays for a subscription
- Application sends a receipt to our backend
- User becomes premium
- We charge you $3 for each premium MAU

Let me know if you have any questions

**Comment by inabdev30** [comment]
@nikslushkin I strongly agree with this price plan, but to engage users I think you should think about the daily free bandwidth available per user 50MB/day is too less according to me it should be 500MB/day and then we can engage more users. What you say?
