### ISSUE TITLE
unsafe implementation of HostnameVerifier.

### ISSUE THREAD

**Issue by Vishusarkar** [AnchorFreePartner/hydrasdk-demo-android#93]
i m using hydra sdk in my app i got an notification from google about unsafe implementation of HostnameVerifier.
 can anyone help me to fix this

**Comment by timoshenkoav** [comment]
Hello!
Are you sure you are not using HostnameVerifier in your app? As other apps using the sdk does not have that warning.

**Comment by Dev-Globalsoft7** [comment]
> 
> 
> Hello!
> Are you sure you are not using HostnameVerifier in your app? As other apps using the sdk does not have that warning.

im also getting this notification after update sdk to 3.3.2 , but 3.1.1 google accepting without notification

**Comment by Vishusarkar** [comment]
thanks i fix this

**Comment by zohaib1sahni** [comment]
i'm also getting same warning from google and i'm using 3.3.3.
what's the solution now?

**Comment by timoshenkoav** [comment]
Hello.
We dont use the HostnameVerifier in the sdk. Please check your app and other dependencies
