### ISSUE TITLE
Vpn closed when app closed fully

### ISSUE THREAD

**Issue by AdilSattar1233** [AnchorFreePartner/hydrasdk-demo-android#96]
Its working fine but now its close when app clock from background

**Comment by timoshenkoav** [comment]
Dont understand te issue. Please provide details: steps and logs

**Comment by AdilSattar1233** [comment]
I mean to say when i remove app from background state from phone. Then vpn also closed from notification and its not working

**Comment by AdilSattar1233** [comment]
Kindly check it out on spark 4 device. even i gave permission from optimized state

**Comment by timoshenkoav** [comment]
please share logs

**Comment by timoshenkoav** [comment]
@AdilSattar1233 any news?
