### ISSUE TITLE
implementation sdk could not get

### ISSUE THREAD

**Issue by dianriswandi** [AnchorFreePartner/hydrasdk-demo-android#98]
Could not GET 'https://www.jitpack.io/com/github/AnchorFreePartner/hydra-sdk-android/sdk/3.3.1/sdk-3.3.1.pom'. Received status code 401 from server: Unauthorized

i get these error any solution?

**Comment by msyahrul801** [comment]
Same problem i can't implementation jitpack not found

**Comment by timoshenkoav** [comment]
@dianriswandi @msyahrul801 try now

**Comment by msyahrul801** [comment]
Could not resolve all dependencies for configuration ':app:debugRuntimeClasspath'.
Could not determine artifacts for com.github.AnchorFreePartner.hydra-sdk-android:sdk:3.3.3
Could not get resource 'https://jitpack.io/com/github/AnchorFreePartner/hydra-sdk-android/sdk/3.3.3/sdk-3.3.3.aar'.
Could not HEAD 'https://jitpack.io/com/github/AnchorFreePartner/hydra-sdk-android/sdk/3.3.3/sdk-3.3.3.aar'.
Read timed out

**Comment by timoshenkoav** [comment]
check your internet connection. or https://status.jitpack.io/. SDK is hosted there
